import type { Seance } from '@/types';

export const seances: Seance[] = [
  // ===== Séances futures =====
  {
    id: 'seance-001',
    proId: 'pro-001',
    sportifId: 'sportif-001',
    carteServiceId: 'cs-001',
    date: '2026-04-21T15:00:00',
    dureeMinutes: 60,
    lieu: 'Salle Fitness Park — Paris 11e',
    tarif: 50,
    statut: 'confirmee',
  },
  {
    id: 'seance-002',
    proId: 'pro-001',
    sportifId: 'sportif-001',
    carteServiceId: 'cs-001',
    date: '2026-04-24T10:00:00',
    dureeMinutes: 60,
    lieu: 'Salle Fitness Park — Paris 11e',
    tarif: 50,
    statut: 'confirmee',
  },
  {
    id: 'seance-003',
    proId: 'pro-003',
    sportifId: 'sportif-002',
    carteServiceId: 'cs-005',
    date: '2026-04-22T11:00:00',
    dureeMinutes: 60,
    lieu: 'Studio Zen — Paris 5e',
    tarif: 45,
    statut: 'en_attente',
  },
  {
    id: 'seance-028',
    proId: 'pro-005',
    sportifId: 'sportif-001',
    carteServiceId: 'cs-007',
    date: '2026-04-23T18:00:00',
    dureeMinutes: 60,
    lieu: 'Domicile — Paris 16e',
    tarif: 70,
    statut: 'confirmee',
  },
  {
    id: 'seance-029',
    proId: 'pro-002',
    sportifId: 'sportif-003',
    carteServiceId: 'cs-003',
    date: '2026-04-22T09:00:00',
    dureeMinutes: 90,
    lieu: 'CrossFit Boulogne',
    tarif: 75,
    statut: 'confirmee',
  },
  {
    id: 'seance-030',
    proId: 'pro-004',
    sportifId: 'sportif-007',
    carteServiceId: 'cs-006',
    date: '2026-04-25T17:00:00',
    dureeMinutes: 60,
    lieu: 'Boxing Club — Saint-Denis',
    tarif: 40,
    statut: 'confirmee',
  },
  {
    id: 'seance-031',
    proId: 'pro-003',
    sportifId: 'sportif-008',
    carteServiceId: 'cs-005',
    date: '2026-04-23T09:00:00',
    dureeMinutes: 60,
    lieu: 'Studio Zen — Paris 5e',
    tarif: 45,
    statut: 'confirmee',
  },
  {
    id: 'seance-032',
    proId: 'pro-005',
    sportifId: 'sportif-004',
    carteServiceId: 'cs-008',
    date: '2026-04-26T07:30:00',
    dureeMinutes: 75,
    lieu: 'Parc Boulogne',
    tarif: 65,
    statut: 'en_attente',
  },
  {
    id: 'seance-033',
    proId: 'pro-001',
    sportifId: 'sportif-010',
    carteServiceId: 'cs-001',
    date: '2026-04-28T14:00:00',
    dureeMinutes: 60,
    lieu: 'Salle Fitness Park — Paris 11e',
    tarif: 50,
    statut: 'confirmee',
  },
  {
    id: 'seance-034',
    proId: 'pro-002',
    sportifId: 'sportif-009',
    carteServiceId: 'cs-004',
    date: '2026-04-27T08:00:00',
    dureeMinutes: 75,
    lieu: 'Stade Charléty — Paris 13e',
    tarif: 65,
    statut: 'confirmee',
  },

  // ===== Séances passées (terminées) =====
  {
    id: 'seance-004',
    proId: 'pro-002',
    sportifId: 'sportif-001',
    carteServiceId: 'cs-003',
    date: '2026-04-15T09:00:00',
    dureeMinutes: 90,
    lieu: 'CrossFit Boulogne',
    tarif: 75,
    statut: 'terminee',
    ressentiClient: 4,
    chargePercue: 8,
    compteRenduCoach:
      "Très bonne séance. Thomas a tenu l'intensité malgré les WODs complexes. Progression notable sur les clean & jerk.",
  },
  {
    id: 'seance-005',
    proId: 'pro-001',
    sportifId: 'sportif-001',
    carteServiceId: 'cs-001',
    date: '2026-04-12T15:00:00',
    dureeMinutes: 60,
    lieu: 'Salle Fitness Park — Paris 11e',
    tarif: 50,
    statut: 'terminee',
    ressentiClient: 3,
    chargePercue: 6,
    compteRenduCoach:
      'Séance de remise en route. Bilan initial effectué. Thomas a une bonne base cardio mais doit travailler la mobilité.',
  },
  {
    id: 'seance-006',
    proId: 'pro-005',
    sportifId: 'sportif-001',
    carteServiceId: 'cs-007',
    date: '2026-04-10T18:00:00',
    dureeMinutes: 60,
    lieu: 'Domicile — Paris 16e',
    tarif: 70,
    statut: 'terminee',
    ressentiClient: 3,
    chargePercue: 5,
    compteRenduCoach:
      "Première séance d'évaluation. Bilan composition corporelle et définition des objectifs.",
  },
  {
    id: 'seance-008',
    proId: 'pro-003',
    sportifId: 'sportif-002',
    carteServiceId: 'cs-005',
    date: '2026-04-08T10:00:00',
    dureeMinutes: 60,
    lieu: 'Studio Zen — Paris 5e',
    tarif: 45,
    statut: 'terminee',
    ressentiClient: 4,
    chargePercue: 3,
    compteRenduCoach:
      "Chloé progresse bien en Vinyasa. La respiration s'améliore nettement. On passe au niveau 2 la semaine prochaine.",
  },
  {
    id: 'seance-009',
    proId: 'pro-001',
    sportifId: 'sportif-005',
    carteServiceId: 'cs-001',
    date: '2026-04-14T10:00:00',
    dureeMinutes: 60,
    lieu: 'Salle Fitness Park — Paris 11e',
    tarif: 50,
    statut: 'terminee',
    ressentiClient: 3,
    chargePercue: 4,
    compteRenduCoach:
      'Première séance avec Antoine. Bilan OK. Attention à la hernie L4-L5. Programme adapté validé.',
  },
  {
    id: 'seance-010',
    proId: 'pro-002',
    sportifId: 'sportif-003',
    carteServiceId: 'cs-003',
    date: '2026-04-08T09:00:00',
    dureeMinutes: 90,
    lieu: 'CrossFit Boulogne',
    tarif: 75,
    statut: 'terminee',
    ressentiClient: 4,
    chargePercue: 9,
    compteRenduCoach:
      'Mehdi pousse fort. PR sur le deadlift à 180 kg. Récupération à surveiller.',
  },
  {
    id: 'seance-011',
    proId: 'pro-004',
    sportifId: 'sportif-007',
    carteServiceId: 'cs-006',
    date: '2026-04-11T17:00:00',
    dureeMinutes: 60,
    lieu: 'Boxing Club — Saint-Denis',
    tarif: 40,
    statut: 'terminee',
    ressentiClient: 4,
    chargePercue: 7,
    compteRenduCoach:
      'Lucas est naturel. Bonne coordination. On continue la technique jab-cross cette semaine.',
  },
  {
    id: 'seance-012',
    proId: 'pro-005',
    sportifId: 'sportif-006',
    carteServiceId: 'cs-009',
    date: '2026-04-09T08:00:00',
    dureeMinutes: 75,
    lieu: 'Salle Olympe — Paris 16e',
    tarif: 70,
    statut: 'terminee',
    ressentiClient: 3,
    chargePercue: 7,
    compteRenduCoach:
      'Fatou a un bon potentiel. Squat à 90 kg validé. Ajuster la nutrition pré-compétition.',
  },
  {
    id: 'seance-013',
    proId: 'pro-001',
    sportifId: 'sportif-001',
    carteServiceId: 'cs-001',
    date: '2026-04-05T15:00:00',
    dureeMinutes: 60,
    lieu: 'Salle Fitness Park — Paris 11e',
    tarif: 50,
    statut: 'terminee',
    ressentiClient: 3,
    chargePercue: 6,
    compteRenduCoach: 'Circuit training bien supporté. Thomas gagne en endurance.',
  },
  {
    id: 'seance-014',
    proId: 'pro-003',
    sportifId: 'sportif-016',
    carteServiceId: 'cs-005',
    date: '2026-04-07T09:00:00',
    dureeMinutes: 60,
    lieu: 'Studio Zen — Paris 5e',
    tarif: 45,
    statut: 'terminee',
    ressentiClient: 4,
    chargePercue: 2,
    compteRenduCoach:
      'Camille est très réceptive. Excellente séance de Yin yoga. Souplesse en nette amélioration.',
  },
  {
    id: 'seance-015',
    proId: 'pro-002',
    sportifId: 'sportif-009',
    carteServiceId: 'cs-004',
    date: '2026-04-06T08:00:00',
    dureeMinutes: 75,
    lieu: 'Stade Charléty — Paris 13e',
    tarif: 65,
    statut: 'terminee',
    ressentiClient: 3,
    chargePercue: 7,
    compteRenduCoach:
      'Séance fractionné 8×400m. Karim tient le pace sub-3h. Travail en côte la semaine prochaine.',
  },
  {
    id: 'seance-016',
    proId: 'pro-005',
    sportifId: 'sportif-011',
    carteServiceId: 'cs-009',
    date: '2026-04-13T10:00:00',
    dureeMinutes: 75,
    lieu: 'Salle Olympe — Paris 16e',
    tarif: 70,
    statut: 'terminee',
    ressentiClient: 3,
    chargePercue: 6,
    compteRenduCoach:
      'Yann progresse bien sur le bench press. +5 kg cette semaine. Ajuster le volume sur les jambes.',
  },
  {
    id: 'seance-017',
    proId: 'pro-001',
    sportifId: 'sportif-018',
    carteServiceId: 'cs-001',
    date: '2026-04-14T16:00:00',
    dureeMinutes: 60,
    lieu: 'Salle Fitness Park — Paris 11e',
    tarif: 50,
    statut: 'terminee',
    ressentiClient: 3,
    chargePercue: 5,
    compteRenduCoach:
      'Première séance avec Julie. Très motivée. Plan progressif sur 3 mois mis en place.',
  },
  {
    id: 'seance-018',
    proId: 'pro-004',
    sportifId: 'sportif-020',
    carteServiceId: 'cs-006',
    date: '2026-04-16T18:00:00',
    dureeMinutes: 60,
    lieu: 'Boxing Club — Saint-Denis',
    tarif: 40,
    statut: 'terminee',
    ressentiClient: 4,
    chargePercue: 6,
    compteRenduCoach:
      'Nadia accroche bien ! Bon cardio, bonne coordination. Elle va progresser vite.',
  },
  {
    id: 'seance-019',
    proId: 'pro-005',
    sportifId: 'sportif-015',
    carteServiceId: 'cs-009',
    date: '2026-04-11T07:00:00',
    dureeMinutes: 75,
    lieu: 'Salle Olympe — Paris 16e',
    tarif: 70,
    statut: 'terminee',
    ressentiClient: 4,
    chargePercue: 9,
    compteRenduCoach:
      'Hugo est une machine. 5×5 squat à 140 kg. Programme force pure en cours.',
  },
  {
    id: 'seance-020',
    proId: 'pro-003',
    sportifId: 'sportif-002',
    carteServiceId: 'cs-005',
    date: '2026-04-01T10:00:00',
    dureeMinutes: 60,
    lieu: 'Studio Zen — Paris 5e',
    tarif: 45,
    statut: 'terminee',
    ressentiClient: 3,
    chargePercue: 3,
    compteRenduCoach:
      'Chloé découvre le Yin. Très bon relâchement. Séance idéale pour son profil.',
  },

  // ===== Séances passées (mars) =====
  {
    id: 'seance-021',
    proId: 'pro-001',
    sportifId: 'sportif-001',
    carteServiceId: 'cs-001',
    date: '2026-03-29T10:00:00',
    dureeMinutes: 60,
    lieu: 'Salle Fitness Park — Paris 11e',
    tarif: 50,
    statut: 'terminee',
    ressentiClient: 2,
    chargePercue: 7,
    compteRenduCoach:
      'Séance difficile. Thomas revient de vacances, perte de rythme. Reprendre doucement.',
  },
  {
    id: 'seance-022',
    proId: 'pro-002',
    sportifId: 'sportif-003',
    carteServiceId: 'cs-003',
    date: '2026-03-25T09:00:00',
    dureeMinutes: 90,
    lieu: 'CrossFit Boulogne',
    tarif: 75,
    statut: 'terminee',
    ressentiClient: 4,
    chargePercue: 8,
    compteRenduCoach: 'Benchmark Fran en 4:12. Record personnel pour Mehdi !',
  },
  {
    id: 'seance-023',
    proId: 'pro-005',
    sportifId: 'sportif-001',
    carteServiceId: 'cs-007',
    date: '2026-03-27T18:00:00',
    dureeMinutes: 60,
    lieu: 'Domicile — Paris 16e',
    tarif: 70,
    statut: 'terminee',
    ressentiClient: 3,
    chargePercue: 5,
    compteRenduCoach:
      'Suivi nutrition. Thomas tient le déficit calorique. -1.2 kg cette quinzaine.',
  },
  {
    id: 'seance-024',
    proId: 'pro-001',
    sportifId: 'sportif-001',
    carteServiceId: 'cs-001',
    date: '2026-03-22T15:00:00',
    dureeMinutes: 60,
    lieu: 'Salle Fitness Park — Paris 11e',
    tarif: 50,
    statut: 'terminee',
    ressentiClient: 3,
    chargePercue: 6,
    compteRenduCoach: 'Bonne séance. Focus mobilité épaule. Am��lioration notable.',
  },
  {
    id: 'seance-025',
    proId: 'pro-003',
    sportifId: 'sportif-008',
    carteServiceId: 'cs-005',
    date: '2026-03-20T09:00:00',
    dureeMinutes: 60,
    lieu: 'Studio Zen — Paris 5e',
    tarif: 45,
    statut: 'terminee',
    ressentiClient: 4,
    chargePercue: 2,
    compteRenduCoach:
      'Sophie est très appliquée. La cheville tient bien. On peut intensifier les postures debout.',
  },
  {
    id: 'seance-026',
    proId: 'pro-002',
    sportifId: 'sportif-015',
    carteServiceId: 'cs-003',
    date: '2026-03-18T08:00:00',
    dureeMinutes: 90,
    lieu: 'CrossFit Boulogne',
    tarif: 75,
    statut: 'terminee',
    ressentiClient: 4,
    chargePercue: 9,
    compteRenduCoach:
      'Hugo enchaîne les PRs. Muscle-up maîtrisé. Ajuster le volume pour éviter la blessure.',
  },

  // ===== Annulée =====
  {
    id: 'seance-007',
    proId: 'pro-001',
    sportifId: 'sportif-001',
    carteServiceId: 'cs-001',
    date: '2026-03-29T15:00:00',
    dureeMinutes: 60,
    lieu: 'Salle Fitness Park — Paris 11e',
    tarif: 50,
    statut: 'annulee',
  },
  {
    id: 'seance-027',
    proId: 'pro-005',
    sportifId: 'sportif-004',
    carteServiceId: 'cs-008',
    date: '2026-04-02T07:30:00',
    dureeMinutes: 75,
    lieu: 'Parc Boulogne',
    tarif: 65,
    statut: 'annulee',
  },
];
