import type { Sportif } from '@/types';

export const sportifs: Sportif[] = [
  {
    id: 'sportif-001',
    prenom: 'Thomas',
    nom: 'LEROY',
    age: 28,
    genre: 'homme',
    photo:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&q=80',
    niveau: 'intermediaire',
    objectifs: ['perte_poids', 'bien_etre'],
    sports: ['fitness', 'running'],
    contraintes: 'Légère tendinite épaule droite',
    frequence: '2-3x',
    ville: 'Paris 11e',
    codePostal: '75011',
    rayonKm: 10,
    budgetMin: 40,
    budgetMax: 70,
    vibe: { pedagogieDiscipline: 4, suiviAutonomie: 3, dataRessenti: 5 },
    bio: 'Développeur web en reconversion sportive. Après 5 ans sans activité, je veux retrouver la forme et perdre les kilos accumulés.',
    clientDepuis: '2026-02-15',
  },
  {
    id: 'sportif-002',
    prenom: 'Chloé',
    nom: 'DUVAL',
    age: 34,
    genre: 'femme',
    photo:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&q=80',
    niveau: 'debutant',
    objectifs: ['bien_etre', 'perte_poids'],
    sports: ['yoga', 'fitness'],
    frequence: '2-3x',
    ville: 'Paris 5e',
    codePostal: '75005',
    rayonKm: 8,
    budgetMin: 35,
    budgetMax: 55,
    vibe: { pedagogieDiscipline: 2, suiviAutonomie: 4, dataRessenti: 8 },
    bio: 'Maman de deux enfants, je cherche à retrouver du temps pour moi à travers le sport. Ambiance bienveillante souhaitée.',
    clientDepuis: '2026-03-01',
  },
  {
    id: 'sportif-003',
    prenom: 'Mehdi',
    nom: 'BELKACEM',
    age: 22,
    genre: 'homme',
    photo:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&q=80',
    niveau: 'avance',
    objectifs: ['preparation_competition', 'prise_masse'],
    sports: ['musculation', 'crossfit'],
    frequence: '4+',
    ville: 'Saint-Denis',
    codePostal: '93200',
    rayonKm: 15,
    budgetMin: 50,
    budgetMax: 90,
    vibe: { pedagogieDiscipline: 9, suiviAutonomie: 7, dataRessenti: 2 },
    bio: 'Compétiteur CrossFit catégorie amateur. Je cherche un prépa physique pour passer au niveau supérieur.',
    clientDepuis: '2026-01-10',
  },
  {
    id: 'sportif-004',
    prenom: 'Léa',
    nom: 'ROUSSEAU',
    age: 26,
    genre: 'femme',
    photo:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&q=80',
    niveau: 'intermediaire',
    objectifs: ['bien_etre', 'perte_poids'],
    sports: ['running', 'yoga'],
    frequence: '2-3x',
    ville: 'Boulogne-Billancourt',
    codePostal: '92100',
    rayonKm: 10,
    budgetMin: 40,
    budgetMax: 65,
    vibe: { pedagogieDiscipline: 3, suiviAutonomie: 5, dataRessenti: 7 },
    bio: 'Avocate stressée cherchant un exutoire sportif. Running le matin, yoga le soir.',
    clientDepuis: '2026-03-20',
  },
  {
    id: 'sportif-005',
    prenom: 'Antoine',
    nom: 'MOREAU',
    age: 45,
    genre: 'homme',
    photo:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&q=80',
    niveau: 'debutant',
    objectifs: ['perte_poids', 'bien_etre'],
    sports: ['fitness', 'natation'],
    contraintes: 'Hernie discale L4-L5, éviter les charges lourdes',
    frequence: '1x',
    ville: 'Vincennes',
    codePostal: '94300',
    rayonKm: 8,
    budgetMin: 40,
    budgetMax: 60,
    vibe: { pedagogieDiscipline: 2, suiviAutonomie: 3, dataRessenti: 6 },
    bio: "Cadre dirigeant de 45 ans, sédentaire depuis trop longtemps. Besoin d'un coach patient et à l'écoute.",
    clientDepuis: '2026-04-01',
  },
  {
    id: 'sportif-006',
    prenom: 'Fatou',
    nom: 'DIALLO',
    age: 30,
    genre: 'femme',
    photo:
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=400&fit=crop&q=80',
    niveau: 'intermediaire',
    objectifs: ['prise_masse', 'preparation_competition'],
    sports: ['musculation', 'fitness'],
    frequence: '4+',
    ville: 'Montreuil',
    codePostal: '93100',
    rayonKm: 12,
    budgetMin: 45,
    budgetMax: 75,
    vibe: { pedagogieDiscipline: 7, suiviAutonomie: 6, dataRessenti: 3 },
    bio: 'Passionnée de fitness depuis 3 ans, je prépare ma première compétition bikini. Besoin de structure et de rigueur.',
    clientDepuis: '2026-02-20',
  },
  {
    id: 'sportif-007',
    prenom: 'Lucas',
    nom: 'PETIT',
    age: 19,
    genre: 'homme',
    photo:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&q=80',
    niveau: 'debutant',
    objectifs: ['prise_masse', 'bien_etre'],
    sports: ['musculation', 'boxe'],
    frequence: '2-3x',
    ville: 'Paris 18e',
    codePostal: '75018',
    rayonKm: 8,
    budgetMin: 30,
    budgetMax: 50,
    vibe: { pedagogieDiscipline: 6, suiviAutonomie: 4, dataRessenti: 5 },
    bio: 'Étudiant en L2, je veux prendre du muscle et apprendre les bases de la boxe.',
    clientDepuis: '2026-03-15',
  },
  {
    id: 'sportif-008',
    prenom: 'Sophie',
    nom: 'LAMBERT',
    age: 38,
    genre: 'femme',
    photo:
      'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=400&fit=crop&q=80',
    niveau: 'intermediaire',
    objectifs: ['bien_etre', 'post_blessure'],
    sports: ['yoga', 'natation'],
    contraintes: 'Reprise post-entorse cheville droite',
    frequence: '2-3x',
    ville: 'Neuilly-sur-Seine',
    codePostal: '92200',
    rayonKm: 10,
    budgetMin: 50,
    budgetMax: 80,
    vibe: { pedagogieDiscipline: 1, suiviAutonomie: 3, dataRessenti: 9 },
    bio: 'DRH en reconversion, le yoga a changé ma vie. Je cherche un accompagnement doux pour revenir après ma blessure.',
    clientDepuis: '2026-03-10',
  },
  {
    id: 'sportif-009',
    prenom: 'Karim',
    nom: 'HASSAN',
    age: 32,
    genre: 'homme',
    photo:
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=400&fit=crop&q=80',
    niveau: 'avance',
    objectifs: ['preparation_competition'],
    sports: ['running', 'crossfit'],
    frequence: '4+',
    ville: 'Levallois-Perret',
    codePostal: '92300',
    rayonKm: 12,
    budgetMin: 55,
    budgetMax: 85,
    vibe: { pedagogieDiscipline: 8, suiviAutonomie: 8, dataRessenti: 1 },
    bio: 'Marathonien 3h15, objectif sub-3h au marathon de Paris 2027. Full data, full discipline.',
    clientDepuis: '2026-01-05',
  },
  {
    id: 'sportif-010',
    prenom: 'Emma',
    nom: 'GARCIA',
    age: 24,
    genre: 'femme',
    photo:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&q=80',
    niveau: 'debutant',
    objectifs: ['bien_etre', 'perte_poids'],
    sports: ['fitness', 'yoga'],
    frequence: '1x',
    ville: 'Paris 14e',
    codePostal: '75014',
    rayonKm: 6,
    budgetMin: 30,
    budgetMax: 50,
    vibe: { pedagogieDiscipline: 2, suiviAutonomie: 2, dataRessenti: 7 },
    bio: "Graphiste freelance. Je bouge pas assez, je le sais. Besoin d'être accompagnée et motivée.",
    clientDepuis: '2026-04-05',
  },
  {
    id: 'sportif-011',
    prenom: 'Yann',
    nom: 'NGUYEN',
    age: 29,
    genre: 'homme',
    photo:
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=400&fit=crop&q=80',
    niveau: 'intermediaire',
    objectifs: ['prise_masse', 'bien_etre'],
    sports: ['musculation', 'tennis'],
    frequence: '2-3x',
    ville: 'Issy-les-Moulineaux',
    codePostal: '92130',
    rayonKm: 10,
    budgetMin: 45,
    budgetMax: 70,
    vibe: { pedagogieDiscipline: 5, suiviAutonomie: 6, dataRessenti: 4 },
    bio: 'Ingénieur data, je fais du tennis le weekend et de la muscu en semaine. Je cherche un coach pour structurer le tout.',
    clientDepuis: '2026-02-28',
  },
  {
    id: 'sportif-012',
    prenom: 'Inès',
    nom: 'BENZEMA',
    age: 27,
    genre: 'femme',
    photo:
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&q=80',
    niveau: 'intermediaire',
    objectifs: ['perte_poids', 'preparation_competition'],
    sports: ['running', 'fitness'],
    frequence: '2-3x',
    ville: 'Créteil',
    codePostal: '94000',
    rayonKm: 10,
    budgetMin: 35,
    budgetMax: 60,
    vibe: { pedagogieDiscipline: 6, suiviAutonomie: 5, dataRessenti: 4 },
    bio: "Infirmière, horaires décalés. Je prépare le semi-marathon de Paris. Besoin d'un plan flexible.",
    clientDepuis: '2026-03-05',
  },
  {
    id: 'sportif-013',
    prenom: 'Pierre',
    nom: 'DUBOIS',
    age: 52,
    genre: 'homme',
    photo:
      'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop&q=80',
    niveau: 'debutant',
    objectifs: ['bien_etre', 'post_blessure'],
    sports: ['natation', 'yoga'],
    contraintes: 'Prothèse genou droit. Pas de course ni de sauts.',
    frequence: '1x',
    ville: 'Versailles',
    codePostal: '78000',
    rayonKm: 8,
    budgetMin: 50,
    budgetMax: 80,
    vibe: { pedagogieDiscipline: 1, suiviAutonomie: 2, dataRessenti: 8 },
    bio: "Chef d'entreprise à la retraite. Je veux rester actif malgré mes limites physiques.",
    clientDepuis: '2026-04-10',
  },
  {
    id: 'sportif-014',
    prenom: 'Aïcha',
    nom: 'TRAORE',
    age: 21,
    genre: 'femme',
    photo:
      'https://images.unsplash.com/photo-1523824921871-d6f1a15151f1?w=400&h=400&fit=crop&q=80',
    niveau: 'debutant',
    objectifs: ['bien_etre', 'perte_poids'],
    sports: ['boxe', 'fitness'],
    frequence: '2-3x',
    ville: 'Nanterre',
    codePostal: '92000',
    rayonKm: 10,
    budgetMin: 25,
    budgetMax: 45,
    vibe: { pedagogieDiscipline: 5, suiviAutonomie: 3, dataRessenti: 6 },
    bio: "Étudiante en droit, je veux me défouler après les cours. La boxe m'attire mais j'ai jamais essayé.",
    clientDepuis: '2026-04-08',
  },
  {
    id: 'sportif-015',
    prenom: 'Hugo',
    nom: 'FERNANDEZ',
    age: 35,
    genre: 'homme',
    photo:
      'https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=400&h=400&fit=crop&q=80',
    niveau: 'avance',
    objectifs: ['preparation_competition', 'prise_masse'],
    sports: ['crossfit', 'musculation', 'running'],
    frequence: '4+',
    ville: 'Paris 16e',
    codePostal: '75016',
    rayonKm: 15,
    budgetMin: 60,
    budgetMax: 90,
    vibe: { pedagogieDiscipline: 9, suiviAutonomie: 9, dataRessenti: 1 },
    bio: 'Ex-militaire reconverti dans le coaching. Entraînement strict, objectifs clairs, zéro excuses.',
    clientDepuis: '2025-11-20',
  },
  {
    id: 'sportif-016',
    prenom: 'Camille',
    nom: 'MARTIN',
    age: 31,
    genre: 'femme',
    photo:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&q=80',
    niveau: 'intermediaire',
    objectifs: ['bien_etre'],
    sports: ['yoga', 'fitness'],
    frequence: '2-3x',
    ville: 'Paris 6e',
    codePostal: '75006',
    rayonKm: 6,
    budgetMin: 45,
    budgetMax: 70,
    vibe: { pedagogieDiscipline: 2, suiviAutonomie: 5, dataRessenti: 9 },
    bio: "Journaliste culture. Le yoga est ma méditation. Je cherche une prof qui comprend que le sport c'est aussi de l'écoute de soi.",
    clientDepuis: '2026-02-01',
  },
  {
    id: 'sportif-017',
    prenom: 'Ousmane',
    nom: 'CISSÉ',
    age: 25,
    genre: 'homme',
    photo:
      'https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=400&h=400&fit=crop&q=80',
    niveau: 'intermediaire',
    objectifs: ['preparation_competition'],
    sports: ['football', 'fitness'],
    frequence: '4+',
    ville: 'Bobigny',
    codePostal: '93000',
    rayonKm: 15,
    budgetMin: 30,
    budgetMax: 55,
    vibe: { pedagogieDiscipline: 7, suiviAutonomie: 5, dataRessenti: 4 },
    bio: 'Footballeur amateur en D3 régionale. Je veux un prépa physique pour gagner en explosivité et en endurance.',
    clientDepuis: '2026-03-01',
  },
  {
    id: 'sportif-018',
    prenom: 'Julie',
    nom: 'BARON',
    age: 40,
    genre: 'femme',
    photo:
      'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop&q=80',
    niveau: 'debutant',
    objectifs: ['perte_poids', 'bien_etre'],
    sports: ['fitness', 'running'],
    frequence: '1x',
    ville: 'Paris 9e',
    codePostal: '75009',
    rayonKm: 8,
    budgetMin: 40,
    budgetMax: 65,
    vibe: { pedagogieDiscipline: 3, suiviAutonomie: 2, dataRessenti: 6 },
    bio: "Comptable, bureau 8h par jour. J'ai pris 12 kg en 3 ans. Je veux un coach qui me tient par la main sans me crier dessus.",
    clientDepuis: '2026-04-12',
  },
  {
    id: 'sportif-019',
    prenom: 'Romain',
    nom: 'LECLERC',
    age: 33,
    genre: 'homme',
    photo:
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&q=80',
    niveau: 'intermediaire',
    objectifs: ['prise_masse', 'bien_etre'],
    sports: ['musculation', 'natation'],
    frequence: '2-3x',
    ville: 'Paris 15e',
    codePostal: '75015',
    rayonKm: 10,
    budgetMin: 45,
    budgetMax: 70,
    vibe: { pedagogieDiscipline: 5, suiviAutonomie: 6, dataRessenti: 3 },
    bio: 'Product manager, 3 ans de muscu en autonomie. Je veux un coach pour casser les plateaux et corriger ma technique.',
    clientDepuis: '2026-02-10',
  },
  {
    id: 'sportif-020',
    prenom: 'Nadia',
    nom: 'AMMAR',
    age: 29,
    genre: 'femme',
    photo:
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop&q=80',
    niveau: 'debutant',
    objectifs: ['bien_etre', 'perte_poids'],
    sports: ['boxe', 'fitness'],
    frequence: '2-3x',
    ville: 'Paris 20e',
    codePostal: '75020',
    rayonKm: 8,
    budgetMin: 30,
    budgetMax: 50,
    vibe: { pedagogieDiscipline: 6, suiviAutonomie: 4, dataRessenti: 5 },
    bio: "Designeuse UX. La boxe c'est mon anti-stress. Je cherche un coach qui mélange technique et cardio.",
    clientDepuis: '2026-03-25',
  },
];

/** Le sportif mock utilisé par défaut en mode démo */
export const defaultSportif = sportifs[0]!;
