import type { Pro } from '@/types';

export const prosCoachs: Pro[] = [
  {
    id: 'pro-001',
    prenom: 'Marine',
    nom: 'BERTRAND',
    photo:
      'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['fitness', 'musculation'],
    bio: "Coach depuis 8 ans, spécialisée dans la perte de poids et la remise en forme. J'accompagne chaque client avec un programme personnalisé et une approche bienveillante. Ma philosophie : le sport doit rester un plaisir.",
    anneesExperience: 8,
    formations: ['BPJEPS AF', 'Certification pré/post-natal'],
    ville: 'Paris 11e',
    codePostal: '75011',
    rayonKm: 10,
    formats: ['presentiel', 'distanciel'],
    formule: 'premium',
    note: 4.7,
    nbAvis: 14,
    avis: [
      {
        id: 'avis-001',
        auteur: 'Thomas M.',
        note: 5,
        date: '2026-03-22',
        commentaire:
          "Marine est exceptionnelle. Programme sur mesure et toujours à l'écoute. J'ai perdu 8 kg en 3 mois.",
      },
      {
        id: 'avis-002',
        auteur: 'Sophie L.',
        note: 5,
        date: '2026-03-10',
        commentaire:
          'Très pédagogue, elle explique chaque mouvement. Je me sens en confiance à chaque séance.',
      },
      {
        id: 'avis-003',
        auteur: 'Karim B.',
        note: 4,
        date: '2026-02-28',
        commentaire:
          'Bons résultats, parfois un peu en retard mais les séances sont toujours de qualité.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-001',
        nom: 'Remise en forme',
        sport: 'fitness',
        description:
          'Programme complet adapté à votre niveau pour retrouver la forme durablement.',
        tarifHeure: 50,
        dureeMinutes: 60,
        tags: ['perte_poids', 'cardio', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 47,
        caGenere: 2350,
      },
      {
        id: 'cs-002',
        nom: 'Musculation guidée',
        sport: 'musculation',
        description: 'Séances de musculation avec technique et progression structurée.',
        tarifHeure: 55,
        dureeMinutes: 75,
        tags: ['prise_masse', 'musculation', 'performance'],
        format: 'presentiel',
        actif: true,
        nbReservations: 32,
        caGenere: 1760,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 50,
    tarifMax: 55,
    vibe: { pedagogieDiscipline: 3, suiviAutonomie: 3, dataRessenti: 6 },
  },
  {
    id: 'pro-003',
    prenom: 'Léa',
    nom: 'CHEN',
    photo:
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['yoga', 'fitness'],
    bio: "Professeure de yoga certifiée et coach bien-être. J'aide mes élèves à retrouver l'harmonie entre le corps et l'esprit. Spécialisée en Vinyasa et Yin yoga, avec une approche douce et intuitive.",
    anneesExperience: 6,
    formations: ['RYT-500 Yoga Alliance', 'BPJEPS AF'],
    ville: 'Paris 5e',
    codePostal: '75005',
    rayonKm: 8,
    formats: ['presentiel', 'distanciel', 'hybride'],
    formule: 'premium',
    note: 4.8,
    nbAvis: 18,
    avis: [
      {
        id: 'avis-006',
        auteur: 'Emma V.',
        note: 5,
        date: '2026-04-01',
        commentaire:
          'Léa a transformé ma pratique du yoga. Son approche est à la fois exigeante et bienveillante.',
      },
      {
        id: 'avis-007',
        auteur: 'Pierre-Antoine G.',
        note: 5,
        date: '2026-03-15',
        commentaire:
          "Je n'avais jamais fait de yoga. Léa m'a mis à l'aise dès la première séance. Addictif !",
      },
    ],
    cartesServices: [
      {
        id: 'cs-005',
        nom: 'Yoga Vinyasa',
        sport: 'yoga',
        description:
          'Séance de Vinyasa flow adaptée à votre niveau. Travail de souffle et de postures.',
        tarifHeure: 45,
        dureeMinutes: 60,
        tags: ['bien_etre', 'souplesse', 'relaxation'],
        format: 'hybride',
        actif: true,
        nbReservations: 56,
        caGenere: 2520,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 45,
    tarifMax: 45,
    vibe: { pedagogieDiscipline: 2, suiviAutonomie: 5, dataRessenti: 9 },
  },
  {
    id: 'pro-004',
    prenom: 'Abdel',
    nom: 'KADDOURI',
    photo:
      'https://images.unsplash.com/photo-1583468982228-19f19164aee2?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['boxe', 'fitness'],
    bio: 'Ancien boxeur amateur, je transmets les valeurs du ring : discipline, respect et dépassement de soi. Mes séances sont intenses mais toujours dans la bonne humeur. Idéal pour ceux qui veulent se défouler tout en apprenant la technique.',
    anneesExperience: 10,
    formations: ['BPJEPS Boxe', 'DEJEPS mention boxe'],
    ville: 'Saint-Denis',
    codePostal: '93200',
    rayonKm: 12,
    formats: ['presentiel'],
    formule: 'standard',
    note: 4.6,
    nbAvis: 9,
    avis: [
      {
        id: 'avis-008',
        auteur: 'Nadia F.',
        note: 5,
        date: '2026-03-28',
        commentaire:
          "Abdel est génial ! Je n'avais jamais mis les gants et maintenant je suis accro.",
      },
    ],
    cartesServices: [
      {
        id: 'cs-006',
        nom: 'Boxe initiation & perfectionnement',
        sport: 'boxe',
        description:
          'Cours de boxe anglaise tous niveaux. Technique, condition physique et sparring léger.',
        tarifHeure: 40,
        dureeMinutes: 60,
        tags: ['cardio', 'intensif', 'bien_etre'],
        format: 'presentiel',
        actif: true,
        nbReservations: 34,
        caGenere: 1360,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 40,
    tarifMax: 40,
    vibe: { pedagogieDiscipline: 7, suiviAutonomie: 4, dataRessenti: 7 },
  },
  {
    id: 'pro-006',
    prenom: 'Fatou',
    nom: 'DIALLO',
    photo:
      'https://images.unsplash.com/photo-1609899464726-209befab8463?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['fitness', 'running'],
    bio: "Passionnée de sport depuis l'enfance, j'ai fait de ma passion mon métier. Mon approche se base sur le plaisir et la constance. Chaque client est unique et mérite un programme qui lui ressemble. Ensemble, on va chercher votre meilleure version.",
    anneesExperience: 5,
    formations: ['BPJEPS AF', 'CQP Instructeur fitness'],
    ville: 'Montreuil',
    codePostal: '93100',
    rayonKm: 10,
    formats: ['presentiel', 'distanciel'],
    formule: 'standard',
    note: 4.5,
    nbAvis: 11,
    avis: [
      {
        id: 'avis-011',
        auteur: 'Clara M.',
        note: 5,
        date: '2026-03-30',
        commentaire:
          "Fatou est incroyablement motivante. Grâce à elle j'ai repris goût au sport après des années d'inactivité.",
      },
      {
        id: 'avis-012',
        auteur: 'Julien P.',
        note: 4,
        date: '2026-03-12',
        commentaire:
          "Bonne coach, programmes variés. J'aurais aimé un suivi un peu plus poussé entre les séances.",
      },
    ],
    cartesServices: [
      {
        id: 'cs-010',
        nom: 'Coaching remise en forme',
        sport: 'fitness',
        description:
          'Séances dynamiques pour reprendre le sport en douceur et progresser à votre rythme.',
        tarifHeure: 35,
        dureeMinutes: 60,
        tags: ['perte_poids', 'cardio', 'bien_etre'],
        format: 'presentiel',
        actif: true,
        nbReservations: 38,
        caGenere: 1330,
      },
      {
        id: 'cs-011',
        nom: 'Running débutant',
        sport: 'running',
        description:
          'Programme progressif pour débuter la course à pied en toute sécurité.',
        tarifHeure: 30,
        dureeMinutes: 60,
        tags: ['cardio', 'bien_etre'],
        format: 'presentiel',
        actif: true,
        nbReservations: 22,
        caGenere: 660,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 30,
    tarifMax: 35,
    vibe: { pedagogieDiscipline: 2, suiviAutonomie: 6, dataRessenti: 8 },
  },
  {
    id: 'pro-009',
    prenom: 'Théo',
    nom: 'LAMBERT',
    photo:
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['musculation', 'fitness'],
    bio: "Coach muscu depuis 4 ans, ancien compétiteur en bodybuilding naturel. Mon truc c'est de rendre la muscu accessible et fun. Pas de prise de tête, on bosse dur et on rigole. Spécialisé prise de masse et recomposition corporelle.",
    anneesExperience: 4,
    formations: ['BPJEPS AF mention musculation', 'Certification IFBB'],
    ville: 'Vincennes',
    codePostal: '94300',
    rayonKm: 8,
    formats: ['presentiel'],
    formule: 'standard',
    note: 4.4,
    nbAvis: 8,
    avis: [
      {
        id: 'avis-017',
        auteur: 'Maxime G.',
        note: 5,
        date: '2026-03-18',
        commentaire:
          "Théo est super cool et connaît vraiment la muscu. J'ai pris 5 kg de muscle sec en 6 mois.",
      },
      {
        id: 'avis-018',
        auteur: 'Laura V.',
        note: 4,
        date: '2026-02-20',
        commentaire:
          'Ambiance détendue, bon coach. Pourrait être un peu plus structuré dans le suivi.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-016',
        nom: 'Prise de masse',
        sport: 'musculation',
        description:
          'Programme complet de prise de masse musculaire avec nutrition et entraînement.',
        tarifHeure: 40,
        dureeMinutes: 75,
        tags: ['prise_masse', 'musculation', 'nutrition'],
        format: 'presentiel',
        actif: true,
        nbReservations: 29,
        caGenere: 1160,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 40,
    tarifMax: 40,
    vibe: { pedagogieDiscipline: 4, suiviAutonomie: 7, dataRessenti: 6 },
  },
  {
    id: 'pro-011',
    prenom: 'Mamadou',
    nom: 'SYLLA',
    photo:
      'https://images.unsplash.com/photo-1597347316205-36f6c451fc4c?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['football', 'fitness'],
    bio: "Ancien footballeur semi-pro, j'ai décidé de transmettre ma passion du ballon rond. Je travaille la condition physique, la technique et le mental. Mes séances sont intenses et ludiques. Je prends aussi des groupes pour du fitness collectif.",
    anneesExperience: 8,
    formations: ['BPJEPS Football', 'DEJEPS Football'],
    ville: 'Créteil',
    codePostal: '94000',
    rayonKm: 15,
    formats: ['presentiel'],
    formule: 'standard',
    note: 4.5,
    nbAvis: 12,
    avis: [
      {
        id: 'avis-021',
        auteur: 'Yanis L.',
        note: 5,
        date: '2026-04-01',
        commentaire:
          'Mamadou est le meilleur pour progresser au foot. Mon fils a intégré un centre de formation grâce à lui.',
      },
      {
        id: 'avis-022',
        auteur: 'Chloé B.',
        note: 4,
        date: '2026-03-05',
        commentaire:
          'Bonnes séances de fitness en extérieur. Ambiance conviviale et sportive.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-019',
        nom: 'Coaching football individuel',
        sport: 'football',
        description:
          'Séances individuelles de technique et condition physique orientées football.',
        tarifHeure: 45,
        dureeMinutes: 75,
        tags: ['competition', 'cardio', 'performance'],
        format: 'presentiel',
        actif: true,
        nbReservations: 42,
        caGenere: 1890,
      },
      {
        id: 'cs-020',
        nom: 'Fitness outdoor',
        sport: 'fitness',
        description: 'Séances en plein air mêlant cardio, renforcement et jeux sportifs.',
        tarifHeure: 35,
        dureeMinutes: 60,
        tags: ['cardio', 'bien_etre', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 26,
        caGenere: 910,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 35,
    tarifMax: 45,
    vibe: { pedagogieDiscipline: 6, suiviAutonomie: 5, dataRessenti: 7 },
  },
  {
    id: 'pro-012',
    prenom: 'Céline',
    nom: 'DURAND',
    photo:
      'https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['yoga', 'fitness'],
    bio: 'Coach holistique, je combine yoga et fitness pour un corps fort et un esprit apaisé. Mes cours mêlent renforcement musculaire doux et travail de respiration. Idéal pour les personnes stressées qui veulent retrouver un équilibre de vie.',
    anneesExperience: 9,
    formations: ['BPJEPS AF', 'RYT-200 Yoga Alliance', 'Formation Pilates Mat'],
    ville: 'Issy-les-Moulineaux',
    codePostal: '92130',
    rayonKm: 10,
    formats: ['presentiel', 'distanciel', 'hybride'],
    formule: 'premium',
    note: 4.6,
    nbAvis: 14,
    avis: [
      {
        id: 'avis-023',
        auteur: 'Isabelle M.',
        note: 5,
        date: '2026-04-05',
        commentaire:
          "Céline est d'une douceur incroyable. Ses séances me font un bien fou après une semaine de travail.",
      },
      {
        id: 'avis-024',
        auteur: 'Romain T.',
        note: 4,
        date: '2026-03-14',
        commentaire:
          'Très bon mix yoga-fitness. On travaille en profondeur sans se faire mal.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-021',
        nom: 'Yoga doux & renforcement',
        sport: 'yoga',
        description:
          'Séance hybride entre yoga restauratif et renforcement musculaire léger.',
        tarifHeure: 50,
        dureeMinutes: 60,
        tags: ['bien_etre', 'souplesse', 'renforcement', 'relaxation'],
        format: 'hybride',
        actif: true,
        nbReservations: 48,
        caGenere: 2400,
      },
      {
        id: 'cs-022',
        nom: 'Fitness bien-être',
        sport: 'fitness',
        description:
          'Fitness doux orienté santé et gestion du stress. Accessible à tous.',
        tarifHeure: 45,
        dureeMinutes: 60,
        tags: ['bien_etre', 'cardio', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 31,
        caGenere: 1395,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 45,
    tarifMax: 50,
    vibe: { pedagogieDiscipline: 1, suiviAutonomie: 4, dataRessenti: 10 },
  },
  {
    id: 'pro-014',
    prenom: 'Élodie',
    nom: 'FOURNIER',
    photo:
      'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['natation', 'fitness'],
    bio: "Maître-nageuse et coach sportif, la natation est ma passion depuis toujours. J'enseigne la technique de nage, la confiance dans l'eau et la remise en forme aquatique. Mes séances sont adaptées à tous, du débutant au nageur confirmé.",
    anneesExperience: 7,
    formations: ['BPJEPS AAN', 'BPJEPS AF', 'Certificat sauvetage aquatique'],
    ville: 'Paris 15e',
    codePostal: '75015',
    rayonKm: 10,
    formats: ['presentiel'],
    formule: 'standard',
    note: 4.6,
    nbAvis: 11,
    avis: [
      {
        id: 'avis-027',
        auteur: 'Françoise D.',
        note: 5,
        date: '2026-03-30',
        commentaire:
          "Élodie m'a appris à nager à 45 ans. Patiente, pédagogue et rassurante.",
      },
      {
        id: 'avis-028',
        auteur: 'Nicolas H.',
        note: 4,
        date: '2026-03-10',
        commentaire:
          "Bon coaching natation. Ma technique de crawl s'est beaucoup améliorée.",
      },
    ],
    cartesServices: [
      {
        id: 'cs-025',
        nom: 'Natation tous niveaux',
        sport: 'natation',
        description:
          'Cours de natation individuels : apprentissage, perfectionnement technique ou entraînement.',
        tarifHeure: 45,
        dureeMinutes: 60,
        tags: ['cardio', 'bien_etre', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 40,
        caGenere: 1800,
      },
      {
        id: 'cs-026',
        nom: 'Aquafitness',
        sport: 'fitness',
        description:
          'Renforcement musculaire et cardio en milieu aquatique. Doux pour les articulations.',
        tarifHeure: 40,
        dureeMinutes: 45,
        tags: ['cardio', 'renforcement', 'bien_etre'],
        format: 'presentiel',
        actif: true,
        nbReservations: 25,
        caGenere: 1000,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 40,
    tarifMax: 45,
    vibe: { pedagogieDiscipline: 2, suiviAutonomie: 3, dataRessenti: 7 },
  },
  {
    id: 'pro-015',
    prenom: 'Olivier',
    nom: 'MOREL',
    photo:
      'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['running', 'fitness'],
    bio: "Coach running et trail passionné. J'ai couru plus de 30 marathons et 10 ultras. Je partage cette passion avec mes clients en les accompagnant vers leurs objectifs : du 5K au marathon. Mon approche allie plaisir de courir et progression structurée.",
    anneesExperience: 11,
    formations: ['BPJEPS AF', 'Certification FFA entraîneur running', 'DU Trail running'],
    ville: 'Versailles',
    codePostal: '78000',
    rayonKm: 20,
    formats: ['presentiel', 'hybride'],
    formule: 'premium',
    note: 4.7,
    nbAvis: 16,
    avis: [
      {
        id: 'avis-029',
        auteur: 'Stéphane J.',
        note: 5,
        date: '2026-04-06',
        commentaire:
          "Olivier m'a fait passer sous les 3h30 au marathon de Paris. Plan parfait, coaching humain.",
      },
      {
        id: 'avis-030',
        auteur: 'Aurélie N.',
        note: 5,
        date: '2026-03-20',
        commentaire:
          "Super coach qui sait motiver sans mettre la pression. J'ai terminé mon premier semi grâce à lui.",
      },
    ],
    cartesServices: [
      {
        id: 'cs-027',
        nom: 'Plan marathon personnalisé',
        sport: 'running',
        description:
          "Plan d'entraînement marathon complet avec séances encadrées et suivi de progression.",
        tarifHeure: 55,
        dureeMinutes: 75,
        tags: ['competition', 'cardio', 'performance'],
        format: 'hybride',
        actif: true,
        nbReservations: 35,
        caGenere: 1925,
      },
      {
        id: 'cs-028',
        nom: 'Running débutant à intermédiaire',
        sport: 'running',
        description:
          'Programme progressif pour passer de 0 à 10K ou améliorer vos chronos.',
        tarifHeure: 45,
        dureeMinutes: 60,
        tags: ['cardio', 'bien_etre'],
        format: 'presentiel',
        actif: true,
        nbReservations: 28,
        caGenere: 1260,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 45,
    tarifMax: 55,
    vibe: { pedagogieDiscipline: 4, suiviAutonomie: 6, dataRessenti: 5 },
  },
  {
    id: 'pro-016',
    prenom: 'Aïcha',
    nom: 'TOURÉ',
    photo:
      'https://images.unsplash.com/photo-1595078475328-1ab05d0a6a0e?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['fitness', 'yoga'],
    bio: "Coach bien-être spécialisée dans l'accompagnement des femmes. Mes séances combinent fitness doux, yoga et relaxation pour vous aider à vous reconnecter à votre corps. Ambiance bienveillante garantie, zéro jugement.",
    anneesExperience: 5,
    formations: ['BPJEPS AF', 'RYT-200 Yoga Alliance'],
    ville: 'Paris 18e',
    codePostal: '75018',
    rayonKm: 8,
    formats: ['presentiel', 'distanciel'],
    formule: 'standard',
    note: 4.5,
    nbAvis: 10,
    avis: [
      {
        id: 'avis-031',
        auteur: 'Marie-Claire J.',
        note: 5,
        date: '2026-03-25',
        commentaire:
          "Aïcha crée un espace safe et bienveillant. Je me sens enfin à l'aise dans une salle de sport.",
      },
      {
        id: 'avis-032',
        auteur: 'Léonie S.',
        note: 4,
        date: '2026-02-28',
        commentaire:
          'Très bonne coach pour reprendre en douceur. Séances variées et agréables.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-029',
        nom: 'Fitness féminin',
        sport: 'fitness',
        description:
          'Programme de fitness adapté aux femmes : renforcement, cardio doux et stretching.',
        tarifHeure: 35,
        dureeMinutes: 60,
        tags: ['bien_etre', 'renforcement', 'perte_poids'],
        format: 'presentiel',
        actif: true,
        nbReservations: 33,
        caGenere: 1155,
      },
      {
        id: 'cs-030',
        nom: 'Yoga détente',
        sport: 'yoga',
        description: 'Séance de yoga doux orientée relaxation et gestion du stress.',
        tarifHeure: 35,
        dureeMinutes: 60,
        tags: ['relaxation', 'souplesse', 'bien_etre'],
        format: 'distanciel',
        actif: true,
        nbReservations: 20,
        caGenere: 700,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 35,
    tarifMax: 35,
    vibe: { pedagogieDiscipline: 1, suiviAutonomie: 3, dataRessenti: 10 },
  },
  {
    id: 'pro-017',
    prenom: 'Hugo',
    nom: 'DA SILVA',
    photo:
      'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['musculation', 'crossfit'],
    bio: "Coach sportif dynamique et énergique. Fan de CrossFit et de musculation fonctionnelle. J'aime pousser mes clients hors de leur zone de confort dans la bonne humeur. Mon credo : transpirer en s'amusant, et les résultats suivent naturellement.",
    anneesExperience: 3,
    formations: ['BPJEPS AF', 'CrossFit L1'],
    ville: 'Paris 12e',
    codePostal: '75012',
    rayonKm: 10,
    formats: ['presentiel'],
    formule: 'standard',
    note: 4.3,
    nbAvis: 7,
    avis: [
      {
        id: 'avis-033',
        auteur: 'Quentin W.',
        note: 5,
        date: '2026-03-28',
        commentaire:
          'Hugo met une ambiance de dingue en séance. On souffre mais on adore revenir.',
      },
      {
        id: 'avis-034',
        auteur: 'Émilie L.',
        note: 4,
        date: '2026-03-05',
        commentaire:
          "Très motivant, parfois un peu intense pour un débutant mais il s'adapte quand on le dit.",
      },
    ],
    cartesServices: [
      {
        id: 'cs-031',
        nom: 'CrossFit initiation',
        sport: 'crossfit',
        description:
          'Découverte du CrossFit avec apprentissage des mouvements fondamentaux.',
        tarifHeure: 40,
        dureeMinutes: 60,
        tags: ['intensif', 'cardio', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 24,
        caGenere: 960,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 40,
    tarifMax: 40,
    vibe: { pedagogieDiscipline: 6, suiviAutonomie: 8, dataRessenti: 5 },
  },
  {
    id: 'pro-020',
    prenom: 'Samira',
    nom: 'HADJ',
    photo:
      'https://images.unsplash.com/photo-1571731956672-f2b94d7dd0d6?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['fitness', 'musculation'],
    bio: "Coach sportif passionnée par la transformation physique. Ancienne en surpoids, j'ai perdu 25 kg grâce au sport et je sais ce que c'est de partir de zéro. Cette expérience personnelle nourrit mon coaching : empathie, persévérance et résultats concrets.",
    anneesExperience: 6,
    formations: ['BPJEPS AF', 'Certification TRX', 'Formation coaching comportemental'],
    ville: 'Paris 20e',
    codePostal: '75020',
    rayonKm: 10,
    formats: ['presentiel', 'distanciel'],
    formule: 'standard',
    note: 4.7,
    nbAvis: 15,
    avis: [
      {
        id: 'avis-039',
        auteur: 'Karine L.',
        note: 5,
        date: '2026-04-10',
        commentaire:
          "Samira comprend ce qu'on vit quand on part de loin. Elle m'a redonné confiance en moi.",
      },
      {
        id: 'avis-040',
        auteur: 'Mehdi T.',
        note: 5,
        date: '2026-03-18',
        commentaire:
          "Séances top, ambiance chaleureuse. J'ai perdu 12 kg en 5 mois avec elle. Bravo Samira.",
      },
    ],
    cartesServices: [
      {
        id: 'cs-036',
        nom: 'Transformation physique',
        sport: 'fitness',
        description:
          'Programme complet de perte de poids avec coaching mental et suivi nutritionnel.',
        tarifHeure: 45,
        dureeMinutes: 60,
        tags: ['perte_poids', 'renforcement', 'bien_etre', 'nutrition'],
        format: 'presentiel',
        actif: true,
        nbReservations: 52,
        caGenere: 2340,
      },
      {
        id: 'cs-037',
        nom: 'Renforcement musculaire',
        sport: 'musculation',
        description:
          'Séances de renforcement musculaire adaptées pour gagner en tonus et en énergie.',
        tarifHeure: 45,
        dureeMinutes: 60,
        tags: ['renforcement', 'musculation', 'prise_masse'],
        format: 'distanciel',
        actif: true,
        nbReservations: 20,
        caGenere: 900,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 45,
    tarifMax: 45,
    vibe: { pedagogieDiscipline: 3, suiviAutonomie: 2, dataRessenti: 8 },
  },
  {
    id: 'pro-023',
    prenom: 'Moussa',
    nom: 'CAMARA',
    photo:
      'https://images.unsplash.com/photo-1596357395217-80de13130e92?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['boxe', 'crossfit'],
    bio: "Coach sportif spécialisé boxe et entraînement fonctionnel. Mes séances sont un mix de technique de boxe, de cardio haute intensité et de renfo. L'objectif : vous rendre plus fort, plus rapide et plus endurant. Ambiance guerrière mais respectueuse.",
    anneesExperience: 7,
    formations: ['BPJEPS Boxe', 'CrossFit L1', 'Certification kettlebell'],
    ville: 'Aubervilliers',
    codePostal: '93300',
    rayonKm: 12,
    formats: ['presentiel'],
    formule: 'standard',
    note: 4.4,
    nbAvis: 9,
    avis: [
      {
        id: 'avis-045',
        auteur: 'Yann C.',
        note: 5,
        date: '2026-03-30',
        commentaire:
          "Moussa est un coach en or. Ses séances de boxe sont les plus intenses que j'ai faites.",
      },
      {
        id: 'avis-046',
        auteur: 'Jessica T.',
        note: 4,
        date: '2026-02-22',
        commentaire: "Super pour se défouler. On travaille dur mais l'ambiance est top.",
      },
    ],
    cartesServices: [
      {
        id: 'cs-043',
        nom: 'Boxe fitness',
        sport: 'boxe',
        description:
          'Entraînement type boxe fitness : cardio, technique et renforcement.',
        tarifHeure: 40,
        dureeMinutes: 60,
        tags: ['cardio', 'intensif', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 35,
        caGenere: 1400,
      },
      {
        id: 'cs-044',
        nom: 'HIIT CrossFit',
        sport: 'crossfit',
        description:
          'Séances HIIT inspirées du CrossFit. Intensité maximale en 45 minutes.',
        tarifHeure: 40,
        dureeMinutes: 45,
        tags: ['intensif', 'cardio', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 22,
        caGenere: 880,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 40,
    tarifMax: 40,
    vibe: { pedagogieDiscipline: 8, suiviAutonomie: 7, dataRessenti: 4 },
  },
  {
    id: 'pro-026',
    prenom: 'Rachid',
    nom: 'EL IDRISSI',
    photo:
      'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['running', 'crossfit'],
    bio: "Coach trail et ultra-endurance. J'ai terminé l'UTMB et plusieurs ultras de 100 miles. Mon approche est holistique : entraînement, nutrition, mental. Je prépare mes clients pour leurs premiers trails comme pour les compétitions exigeantes.",
    anneesExperience: 9,
    formations: [
      'BPJEPS AF',
      'Certification ITRA trail coaching',
      'Formation nutrition sportive',
    ],
    ville: 'Meudon',
    codePostal: '92190',
    rayonKm: 20,
    formats: ['presentiel', 'hybride'],
    formule: 'premium',
    note: 4.7,
    nbAvis: 13,
    avis: [
      {
        id: 'avis-051',
        auteur: 'Luc P.',
        note: 5,
        date: '2026-04-09',
        commentaire:
          "Rachid m'a préparé pour mon premier ultra de 80 km. Je l'ai terminé grâce à lui, un grand coach.",
      },
      {
        id: 'avis-052',
        auteur: 'Diane G.',
        note: 4,
        date: '2026-03-18',
        commentaire:
          'Excellent connaisseur du trail. Plans très détaillés. Peut être un peu exigeant pour les débutants.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-049',
        nom: 'Prépa trail & ultra',
        sport: 'running',
        description:
          'Programme complet de préparation trail avec sorties en nature et dénivelé.',
        tarifHeure: 55,
        dureeMinutes: 90,
        tags: ['competition', 'cardio', 'performance', 'intensif'],
        format: 'hybride',
        actif: true,
        nbReservations: 30,
        caGenere: 1650,
      },
      {
        id: 'cs-050',
        nom: 'CrossFit endurance',
        sport: 'crossfit',
        description:
          'Mix CrossFit et endurance pour développer une condition physique complète.',
        tarifHeure: 50,
        dureeMinutes: 60,
        tags: ['intensif', 'cardio', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 18,
        caGenere: 900,
      },
    ],
    niveauEnseigne: ['intermediaire', 'avance'],
    tarifMin: 50,
    tarifMax: 55,
    vibe: { pedagogieDiscipline: 7, suiviAutonomie: 8, dataRessenti: 3 },
  },
  {
    id: 'pro-027',
    prenom: 'Inès',
    nom: 'BOUKHRIS',
    photo:
      'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['fitness', 'yoga'],
    bio: 'Coach sportif et instructrice yoga, je crée des programmes qui allient intensité et récupération. Mon approche combine le meilleur du fitness et du yoga pour un corps fonctionnel et un esprit serein. Chaque séance est une aventure.',
    anneesExperience: 4,
    formations: ['BPJEPS AF', 'RYT-200 Yoga Alliance', 'Certification Pilates Reformer'],
    ville: 'Paris 4e',
    codePostal: '75004',
    rayonKm: 8,
    formats: ['presentiel', 'distanciel'],
    formule: 'standard',
    note: 4.3,
    nbAvis: 8,
    avis: [
      {
        id: 'avis-053',
        auteur: 'Anaïs W.',
        note: 5,
        date: '2026-03-25',
        commentaire:
          "Inès propose des séances originales qui mélangent renforcement et détente. J'adore !",
      },
      {
        id: 'avis-054',
        auteur: 'Thibaut M.',
        note: 4,
        date: '2026-02-28',
        commentaire:
          'Bon coaching, séances bien construites. Encore jeune dans le métier mais très prometteuse.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-051',
        nom: 'Yoga & fitness fusion',
        sport: 'yoga',
        description:
          'Séance hybride mêlant postures de yoga, renforcement et stretching dynamique.',
        tarifHeure: 40,
        dureeMinutes: 60,
        tags: ['bien_etre', 'renforcement', 'souplesse'],
        format: 'presentiel',
        actif: true,
        nbReservations: 28,
        caGenere: 1120,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 40,
    tarifMax: 40,
    vibe: { pedagogieDiscipline: 3, suiviAutonomie: 5, dataRessenti: 8 },
  },
  {
    id: 'pro-029',
    prenom: 'Awa',
    nom: 'NDIAYE',
    photo:
      'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['fitness', 'running'],
    bio: "Coach sportif énergique et souriante. Je mets la bonne humeur au coeur de mes séances. Mon approche : des exercices variés, de la musique et beaucoup d'encouragements. Le sport, c'est la fête du corps et je veux que vous kiffez chaque minute.",
    anneesExperience: 3,
    formations: ['BPJEPS AF', 'Certification Les Mills'],
    ville: 'Pantin',
    codePostal: '93500',
    rayonKm: 10,
    formats: ['presentiel'],
    formule: 'standard',
    note: 4.2,
    nbAvis: 6,
    avis: [
      {
        id: 'avis-057',
        auteur: 'Justine H.',
        note: 5,
        date: '2026-03-22',
        commentaire:
          "Awa est un rayon de soleil ! Ses séances sont un vrai bonheur. On transpire en s'amusant.",
      },
      {
        id: 'avis-058',
        auteur: 'Bruno S.',
        note: 4,
        date: '2026-02-18',
        commentaire:
          'Bonne énergie, séances fun. Manque parfois un peu de structure technique.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-054',
        nom: 'Fitness fun & cardio',
        sport: 'fitness',
        description:
          'Séances cardio dynamiques et joyeuses. Danse, HIIT et renforcement en musique.',
        tarifHeure: 30,
        dureeMinutes: 60,
        tags: ['cardio', 'bien_etre', 'perte_poids'],
        format: 'presentiel',
        actif: true,
        nbReservations: 20,
        caGenere: 600,
      },
      {
        id: 'cs-055',
        nom: 'Running en groupe',
        sport: 'running',
        description:
          'Sorties running conviviales avec exercices de renforcement intégrés.',
        tarifHeure: 25,
        dureeMinutes: 60,
        tags: ['cardio', 'bien_etre'],
        format: 'presentiel',
        actif: true,
        nbReservations: 15,
        caGenere: 375,
      },
    ],
    niveauEnseigne: ['debutant'],
    tarifMin: 25,
    tarifMax: 30,
    vibe: { pedagogieDiscipline: 2, suiviAutonomie: 7, dataRessenti: 9 },
  },
  {
    id: 'pro-031',
    prenom: 'Yasmine',
    nom: 'FERHAT',
    photo:
      'https://images.unsplash.com/photo-1609899464726-209befab8463?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['fitness', 'musculation'],
    bio: "Coach sportif certifiée, passionnée par l'empowerment féminin par le sport. Je casse les codes : les femmes peuvent soulever lourd et c'est beau. Mes programmes sont intenses, progressifs et toujours adaptés à vos objectifs.",
    anneesExperience: 5,
    formations: ['BPJEPS AF', 'Certification StrongFirst Kettlebell'],
    ville: 'Argenteuil',
    codePostal: '95100',
    rayonKm: 12,
    formats: ['presentiel', 'distanciel'],
    formule: 'standard',
    note: 4.5,
    nbAvis: 10,
    avis: [
      {
        id: 'avis-061',
        auteur: 'Mélanie D.',
        note: 5,
        date: '2026-03-28',
        commentaire:
          "Yasmine m'a fait découvrir la muscu. Je soulève 60 kg au squat et je suis fière de moi.",
      },
      {
        id: 'avis-062',
        auteur: 'Amir K.',
        note: 4,
        date: '2026-03-08',
        commentaire: 'Bonne coach, séances bien construites et progressives. Recommandé.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-058',
        nom: 'Musculation au féminin',
        sport: 'musculation',
        description:
          'Programme de musculation adapté aux femmes. Force, confiance et esthétique.',
        tarifHeure: 40,
        dureeMinutes: 60,
        tags: ['musculation', 'renforcement', 'prise_masse'],
        format: 'presentiel',
        actif: true,
        nbReservations: 36,
        caGenere: 1440,
      },
      {
        id: 'cs-059',
        nom: 'HIIT & renforcement',
        sport: 'fitness',
        description: 'Séances haute intensité mêlant cardio et renforcement musculaire.',
        tarifHeure: 35,
        dureeMinutes: 45,
        tags: ['intensif', 'cardio', 'perte_poids'],
        format: 'distanciel',
        actif: true,
        nbReservations: 20,
        caGenere: 700,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 35,
    tarifMax: 40,
    vibe: { pedagogieDiscipline: 6, suiviAutonomie: 6, dataRessenti: 5 },
  },
  {
    id: 'pro-034',
    prenom: 'Camille',
    nom: 'RODRIGUEZ',
    photo:
      'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['yoga', 'natation'],
    bio: "Coach spécialisée en yoga Ashtanga et activités aquatiques. Mon parcours atypique m'a menée de la compétition de natation au yoga. J'enseigne une discipline exigeante mais bienveillante, avec le souffle comme fil conducteur entre ces deux pratiques.",
    anneesExperience: 7,
    formations: [
      'BPJEPS AAN',
      'RYT-500 Yoga Alliance',
      'Certification Ashtanga autorisé',
    ],
    ville: 'Paris 19e',
    codePostal: '75019',
    rayonKm: 10,
    formats: ['presentiel', 'hybride'],
    formule: 'premium',
    note: 4.6,
    nbAvis: 13,
    avis: [
      {
        id: 'avis-067',
        auteur: 'Sylvie A.',
        note: 5,
        date: '2026-04-04',
        commentaire:
          'Camille est une perle. Son Ashtanga est exigeant et ses ajustements sont parfaits.',
      },
      {
        id: 'avis-068',
        auteur: 'Damien F.',
        note: 4,
        date: '2026-03-15',
        commentaire:
          'Combinaison natation-yoga originale et très efficace pour la récupération.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-064',
        nom: 'Yoga Ashtanga',
        sport: 'yoga',
        description:
          "Cours d'Ashtanga yoga : séries guidées avec ajustements individuels.",
        tarifHeure: 50,
        dureeMinutes: 75,
        tags: ['bien_etre', 'souplesse', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 44,
        caGenere: 2200,
      },
      {
        id: 'cs-065',
        nom: 'Natation & souffle',
        sport: 'natation',
        description:
          'Séances de natation axées sur le travail respiratoire et la technique de crawl.',
        tarifHeure: 50,
        dureeMinutes: 60,
        tags: ['bien_etre', 'cardio', 'relaxation'],
        format: 'presentiel',
        actif: true,
        nbReservations: 20,
        caGenere: 1000,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 50,
    tarifMax: 50,
    vibe: { pedagogieDiscipline: 6, suiviAutonomie: 5, dataRessenti: 7 },
  },
  {
    id: 'pro-035',
    prenom: 'Ibrahim',
    nom: 'DIOP',
    photo:
      'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['boxe', 'musculation'],
    bio: "Coach boxe et préparation physique. 12 ans de ring en boxe thaï m'ont forgé un caractère d'acier que je transmets à mes élèves. Mes séances sont techniques et physiques. Je suis exigeant mais toujours juste et respectueux.",
    anneesExperience: 12,
    formations: [
      'BPJEPS Boxe',
      'DEJEPS Sports de combat',
      'Certification Muay Thai FFKMDA',
    ],
    ville: 'Ivry-sur-Seine',
    codePostal: '94200',
    rayonKm: 12,
    formats: ['presentiel'],
    formule: 'premium',
    note: 4.7,
    nbAvis: 16,
    avis: [
      {
        id: 'avis-069',
        auteur: 'Kévin L.',
        note: 5,
        date: '2026-04-07',
        commentaire:
          'Ibrahim est une légende. Sa technique et sa pédagogie sont incroyables. Respect.',
      },
      {
        id: 'avis-070',
        auteur: 'Sonia M.',
        note: 5,
        date: '2026-03-18',
        commentaire:
          "J'avais peur de la boxe, Ibrahim m'a mise en confiance dès le premier round. Je suis accro.",
      },
    ],
    cartesServices: [
      {
        id: 'cs-066',
        nom: 'Boxe thaï technique',
        sport: 'boxe',
        description:
          'Cours de boxe thaï : technique de frappe, esquives, enchaînements et sparring contrôlé.',
        tarifHeure: 55,
        dureeMinutes: 75,
        tags: ['competition', 'intensif', 'cardio'],
        format: 'presentiel',
        actif: true,
        nbReservations: 50,
        caGenere: 2750,
      },
      {
        id: 'cs-067',
        nom: 'Prépa physique combat',
        sport: 'musculation',
        description:
          'Renforcement musculaire spécifique sports de combat : explosivité et endurance.',
        tarifHeure: 50,
        dureeMinutes: 60,
        tags: ['musculation', 'intensif', 'performance'],
        format: 'presentiel',
        actif: true,
        nbReservations: 28,
        caGenere: 1400,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 50,
    tarifMax: 55,
    vibe: { pedagogieDiscipline: 9, suiviAutonomie: 6, dataRessenti: 3 },
  },
  {
    id: 'pro-037',
    prenom: 'Kenzo',
    nom: 'TANAKA',
    photo:
      'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['musculation', 'fitness'],
    bio: "Coach sportif spécialisé en musculation et transformation physique. D'origine japonaise, j'ai grandi avec les valeurs de discipline et de constance. Je propose un coaching exigeant mais structuré, avec des résultats garantis pour ceux qui s'investissent.",
    anneesExperience: 6,
    formations: ['BPJEPS AF', 'Certification NASM-CPT', 'Formation nutrition sportive'],
    ville: 'Paris 2e',
    codePostal: '75002',
    rayonKm: 10,
    formats: ['presentiel', 'distanciel'],
    formule: 'premium',
    note: 4.6,
    nbAvis: 12,
    avis: [
      {
        id: 'avis-073',
        auteur: 'Fabien H.',
        note: 5,
        date: '2026-04-03',
        commentaire:
          'Kenzo est méthodique et rigoureux. Mon physique a changé en 4 mois. Le meilleur.',
      },
      {
        id: 'avis-074',
        auteur: 'Nora B.',
        note: 4,
        date: '2026-03-10',
        commentaire:
          'Coach sérieux et compétent. Peut paraître strict mais les résultats suivent.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-070',
        nom: 'Transformation physique homme',
        sport: 'musculation',
        description:
          'Programme intensif de recomposition corporelle : perte de gras et gain musculaire.',
        tarifHeure: 55,
        dureeMinutes: 75,
        tags: ['prise_masse', 'perte_poids', 'musculation'],
        format: 'presentiel',
        actif: true,
        nbReservations: 38,
        caGenere: 2090,
      },
      {
        id: 'cs-071',
        nom: 'Coaching en ligne muscu',
        sport: 'musculation',
        description:
          'Suivi à distance avec programme personnalisé, vidéos de démonstration et ajustements.',
        tarifHeure: 45,
        dureeMinutes: 45,
        tags: ['musculation', 'prise_masse', 'renforcement'],
        format: 'distanciel',
        actif: true,
        nbReservations: 25,
        caGenere: 1125,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 45,
    tarifMax: 55,
    vibe: { pedagogieDiscipline: 9, suiviAutonomie: 5, dataRessenti: 2 },
  },
  {
    id: 'pro-041',
    prenom: 'Raphaël',
    nom: 'COHEN',
    photo:
      'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['crossfit', 'musculation'],
    bio: "Coach CrossFit certifié L3, passionné par l'entraînement fonctionnel depuis 10 ans. Ma box est mon terrain de jeu et chaque WOD est une opportunité de se dépasser. Je coache avec intensité, rigueur et une bonne dose d'humour.",
    anneesExperience: 10,
    formations: ['CrossFit L3', 'BPJEPS AF', 'Certification haltérophilie FFHM'],
    ville: 'Paris 10e',
    codePostal: '75010',
    rayonKm: 10,
    formats: ['presentiel'],
    formule: 'premium',
    note: 4.8,
    nbAvis: 18,
    avis: [
      {
        id: 'avis-081',
        auteur: 'Ludovic S.',
        note: 5,
        date: '2026-04-11',
        commentaire:
          'Raphaël est le meilleur coach CrossFit de Paris. Technique irréprochable et ambiance géniale.',
      },
      {
        id: 'avis-082',
        auteur: 'Manon V.',
        note: 5,
        date: '2026-03-28',
        commentaire:
          'Ses cours sont addictifs. On progresse vite et dans la bonne humeur. Fan absolue.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-079',
        nom: 'CrossFit coaching individuel',
        sport: 'crossfit',
        description:
          'Séances CrossFit individuelles avec programmation sur mesure et suivi technique.',
        tarifHeure: 60,
        dureeMinutes: 75,
        tags: ['intensif', 'performance', 'competition'],
        format: 'presentiel',
        actif: true,
        nbReservations: 52,
        caGenere: 3120,
      },
      {
        id: 'cs-080',
        nom: 'Haltérophilie technique',
        sport: 'musculation',
        description:
          'Travail technique des mouvements olympiques : arraché et épaulé-jeté.',
        tarifHeure: 55,
        dureeMinutes: 60,
        tags: ['performance', 'musculation', 'competition'],
        format: 'presentiel',
        actif: true,
        nbReservations: 30,
        caGenere: 1650,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 55,
    tarifMax: 60,
    vibe: { pedagogieDiscipline: 7, suiviAutonomie: 6, dataRessenti: 4 },
  },
  {
    id: 'pro-042',
    prenom: 'Fatima',
    nom: 'OUAZZANI',
    photo:
      'https://images.unsplash.com/photo-1595078475328-1ab05d0a6a0e?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['fitness', 'running'],
    bio: 'Coach sportif spécialisée en perte de poids et remise en forme post-grossesse. Maman de 3 enfants, je comprends les défis du corps après la maternité. Mon accompagnement est global : sport, nutrition et motivation pour retrouver confiance et énergie.',
    anneesExperience: 7,
    formations: [
      'BPJEPS AF',
      'Certification pré/post-natal De Gasquet',
      'Formation nutrition',
    ],
    ville: 'Sartrouville',
    codePostal: '78500',
    rayonKm: 15,
    formats: ['presentiel', 'distanciel', 'hybride'],
    formule: 'standard',
    note: 4.6,
    nbAvis: 12,
    avis: [
      {
        id: 'avis-083',
        auteur: 'Laetitia M.',
        note: 5,
        date: '2026-04-02',
        commentaire:
          "Fatima comprend parfaitement les besoins des mamans. J'ai retrouvé mon corps d'avant en 6 mois.",
      },
      {
        id: 'avis-084',
        auteur: 'Rachida H.',
        note: 5,
        date: '2026-03-12',
        commentaire:
          'Coach au top, bienveillante et efficace. Ses programmes sont parfaitement adaptés.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-081',
        nom: 'Remise en forme post-natal',
        sport: 'fitness',
        description:
          'Programme progressif de remise en forme après grossesse avec exercices adaptés.',
        tarifHeure: 45,
        dureeMinutes: 60,
        tags: ['perte_poids', 'renforcement', 'bien_etre'],
        format: 'hybride',
        actif: true,
        nbReservations: 40,
        caGenere: 1800,
      },
      {
        id: 'cs-082',
        nom: 'Running mamans',
        sport: 'running',
        description:
          'Reprise progressive de la course à pied après maternité. Sortie poussette bienvenue.',
        tarifHeure: 35,
        dureeMinutes: 45,
        tags: ['cardio', 'bien_etre'],
        format: 'presentiel',
        actif: true,
        nbReservations: 18,
        caGenere: 630,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 35,
    tarifMax: 45,
    vibe: { pedagogieDiscipline: 2, suiviAutonomie: 2, dataRessenti: 9 },
  },
  {
    id: 'pro-044',
    prenom: 'Sakura',
    nom: 'YAMAMOTO',
    photo:
      'https://images.unsplash.com/photo-1552196563-55cd4e45efb3?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['yoga', 'fitness'],
    bio: 'Professeure de yoga Kundalini et coach en respiration. Formée en Inde pendant 2 ans, je propose une approche spirituelle et physique du yoga. Mes cours intègrent mantra, pranayama et postures pour une transformation en profondeur.',
    anneesExperience: 8,
    formations: ['RYT-500 Yoga Alliance', 'Certification Kundalini KRI', 'BPJEPS AF'],
    ville: 'Paris 1er',
    codePostal: '75001',
    rayonKm: 12,
    formats: ['presentiel', 'distanciel', 'hybride'],
    formule: 'premium',
    note: 4.7,
    nbAvis: 14,
    avis: [
      {
        id: 'avis-087',
        auteur: 'Gaëlle S.',
        note: 5,
        date: '2026-04-06',
        commentaire:
          "Sakura m'a initiée au Kundalini. Une expérience profonde et transformatrice. Merci.",
      },
      {
        id: 'avis-088',
        auteur: 'Benoît K.',
        note: 4,
        date: '2026-03-15',
        commentaire:
          'Approche spirituelle qui ne conviendra pas à tout le monde, mais les résultats sur le stress sont réels.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-085',
        nom: 'Yoga Kundalini',
        sport: 'yoga',
        description:
          'Séance de Kundalini yoga : mantras, pranayama, méditation et postures.',
        tarifHeure: 55,
        dureeMinutes: 75,
        tags: ['bien_etre', 'relaxation', 'souplesse'],
        format: 'hybride',
        actif: true,
        nbReservations: 45,
        caGenere: 2475,
      },
      {
        id: 'cs-086',
        nom: 'Breathwork sportif',
        sport: 'fitness',
        description:
          'Techniques avancées de respiration pour optimiser vos performances sportives.',
        tarifHeure: 50,
        dureeMinutes: 45,
        tags: ['bien_etre', 'performance', 'relaxation'],
        format: 'distanciel',
        actif: true,
        nbReservations: 20,
        caGenere: 1000,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 50,
    tarifMax: 55,
    vibe: { pedagogieDiscipline: 1, suiviAutonomie: 3, dataRessenti: 10 },
  },
  {
    id: 'pro-046',
    prenom: 'Hamza',
    nom: 'MEBARKI',
    photo:
      'https://images.unsplash.com/photo-1597347316205-36f6c451fc4c?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['musculation', 'fitness', 'crossfit'],
    bio: "Coach sportif polyvalent, je m'adapte à tous les profils : du sédentaire qui veut bouger au compétiteur qui veut performer. Formé en musculation, CrossFit et nutrition, je propose un accompagnement complet. Mes clients deviennent des athlètes.",
    anneesExperience: 6,
    formations: ['BPJEPS AF', 'CrossFit L1', 'Certification Precision Nutrition'],
    ville: 'Asnières-sur-Seine',
    codePostal: '92600',
    rayonKm: 10,
    formats: ['presentiel', 'distanciel'],
    formule: 'standard',
    note: 4.4,
    nbAvis: 10,
    avis: [
      {
        id: 'avis-091',
        auteur: 'Jordan B.',
        note: 5,
        date: '2026-04-01',
        commentaire:
          'Hamza est un coach complet. Muscu, nutrition, mental : il gère tout. Très satisfait.',
      },
      {
        id: 'avis-092',
        auteur: 'Pauline F.',
        note: 4,
        date: '2026-03-08',
        commentaire:
          "Coach dynamique et à l'écoute. Programme bien structuré et résultats au rendez-vous.",
      },
    ],
    cartesServices: [
      {
        id: 'cs-089',
        nom: 'Programme all-in-one',
        sport: 'fitness',
        description:
          'Programme complet : entraînement, nutrition et suivi de progression mensuel.',
        tarifHeure: 45,
        dureeMinutes: 60,
        tags: ['perte_poids', 'musculation', 'nutrition', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 38,
        caGenere: 1710,
      },
      {
        id: 'cs-090',
        nom: 'Musculation en ligne',
        sport: 'musculation',
        description:
          'Coaching musculation à distance avec vidéos, programme et corrections.',
        tarifHeure: 35,
        dureeMinutes: 45,
        tags: ['prise_masse', 'musculation'],
        format: 'distanciel',
        actif: true,
        nbReservations: 20,
        caGenere: 700,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 35,
    tarifMax: 45,
    vibe: { pedagogieDiscipline: 5, suiviAutonomie: 5, dataRessenti: 5 },
  },
  {
    id: 'pro-048',
    prenom: 'Dimitri',
    nom: 'PAPADOPOULOS',
    photo:
      'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['fitness', 'running', 'musculation'],
    bio: 'Coach sportif généraliste avec une énergie débordante. Ancien sportif universitaire, je propose des séances fun et intenses qui mélangent running, renforcement et challenges. Mon objectif : que vous aimiez tellement le sport que vous ne puissiez plus vous en passer.',
    anneesExperience: 5,
    formations: ['BPJEPS AF', 'Licence STAPS', 'Certification TRX'],
    ville: 'Montrouge',
    codePostal: '92120',
    rayonKm: 10,
    formats: ['presentiel', 'hybride'],
    formule: 'standard',
    note: 4.3,
    nbAvis: 8,
    avis: [
      {
        id: 'avis-095',
        auteur: 'Axel R.',
        note: 5,
        date: '2026-03-30',
        commentaire:
          'Dimitri met une énergie folle dans ses séances. On ne voit pas le temps passer.',
      },
      {
        id: 'avis-096',
        auteur: 'Célia N.',
        note: 4,
        date: '2026-02-22',
        commentaire: 'Bon coach, très motivant. Séances variées et jamais ennuyeuses.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-093',
        nom: 'Bootcamp outdoor',
        sport: 'fitness',
        description:
          'Séances en plein air type bootcamp : circuits, sprints et exercices au poids du corps.',
        tarifHeure: 35,
        dureeMinutes: 60,
        tags: ['cardio', 'intensif', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 30,
        caGenere: 1050,
      },
      {
        id: 'cs-094',
        nom: 'Running & renfo',
        sport: 'running',
        description:
          'Mix running et renforcement musculaire pour un corps complet et endurant.',
        tarifHeure: 35,
        dureeMinutes: 60,
        tags: ['cardio', 'renforcement', 'bien_etre'],
        format: 'presentiel',
        actif: true,
        nbReservations: 18,
        caGenere: 630,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 35,
    tarifMax: 35,
    vibe: { pedagogieDiscipline: 5, suiviAutonomie: 7, dataRessenti: 6 },
  },
  {
    id: 'pro-050',
    prenom: 'Valentin',
    nom: 'MORIN',
    photo:
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&h=400&fit=crop&q=80',
    specialite: 'coach_sportif',
    sports: ['musculation', 'fitness'],
    bio: "Coach sportif spécialisé dans le coaching senior et la remise en forme douce. Après 10 ans en salle de musculation, j'ai découvert ma vocation : accompagner les personnes de plus de 50 ans vers une vie plus active. Patience et bienveillance sont mes valeurs.",
    anneesExperience: 10,
    formations: [
      'BPJEPS AF',
      'Certification Sport Santé',
      'Formation APA (Activités Physiques Adaptées)',
    ],
    ville: 'Fontenay-sous-Bois',
    codePostal: '94120',
    rayonKm: 12,
    formats: ['presentiel', 'distanciel'],
    formule: 'standard',
    note: 4.6,
    nbAvis: 16,
    avis: [
      {
        id: 'avis-099',
        auteur: 'Monique R.',
        note: 5,
        date: '2026-04-09',
        commentaire:
          'Valentin est formidable avec les seniors. À 62 ans, je me sens plus en forme que jamais.',
      },
      {
        id: 'avis-100',
        auteur: 'Gérard P.',
        note: 5,
        date: '2026-03-22',
        commentaire:
          'Enfin un coach qui comprend les besoins des plus de 50 ans. Exercices adaptés et progression douce.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-097',
        nom: 'Fitness senior',
        sport: 'fitness',
        description:
          'Programme de remise en forme adapté aux seniors : mobilité, équilibre et renforcement.',
        tarifHeure: 45,
        dureeMinutes: 60,
        tags: ['bien_etre', 'renforcement', 'mobilite'],
        format: 'presentiel',
        actif: true,
        nbReservations: 55,
        caGenere: 2475,
      },
      {
        id: 'cs-098',
        nom: 'Musculation douce',
        sport: 'musculation',
        description:
          'Musculation adaptée avec charges légères pour maintenir la masse musculaire.',
        tarifHeure: 45,
        dureeMinutes: 60,
        tags: ['renforcement', 'mobilite', 'bien_etre'],
        format: 'presentiel',
        actif: true,
        nbReservations: 30,
        caGenere: 1350,
      },
      {
        id: 'cs-099',
        nom: 'Coaching à domicile senior',
        sport: 'fitness',
        description:
          'Séances à domicile pour les personnes à mobilité réduite ou préférant le confort de chez soi.',
        tarifHeure: 55,
        dureeMinutes: 60,
        tags: ['bien_etre', 'mobilite', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 20,
        caGenere: 1100,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 45,
    tarifMax: 55,
    vibe: { pedagogieDiscipline: 1, suiviAutonomie: 2, dataRessenti: 9 },
  },
];
