import type { Pro } from '@/types';

export const prosEducateurs: Pro[] = [
  {
    id: 'pro-019',
    prenom: 'Franck',
    nom: 'DUPUIS',
    photo:
      'https://images.unsplash.com/photo-1549476464-37392f717541?w=400&h=400&fit=crop&q=80',
    specialite: 'educateur_sportif',
    sports: ['tennis', 'fitness'],
    bio: "Éducateur sportif diplômé avec une spécialité tennis. J'enseigne le tennis depuis 10 ans à tous les publics : enfants, adultes, compétiteurs. Ma pédagogie est ludique et progressive. Le plaisir du jeu est au centre de ma méthode.",
    anneesExperience: 10,
    formations: ['DEJEPS Tennis', 'BPJEPS AF'],
    ville: 'Saint-Germain-en-Laye',
    codePostal: '78100',
    rayonKm: 15,
    formats: ['presentiel'],
    formule: 'standard',
    note: 4.5,
    nbAvis: 14,
    avis: [
      {
        id: 'avis-037',
        auteur: 'Catherine P.',
        note: 5,
        date: '2026-03-22',
        commentaire:
          'Franck est un super prof de tennis. Mon fils a progressé de façon spectaculaire en un an.',
      },
      {
        id: 'avis-038',
        auteur: 'Jean-Marc S.',
        note: 4,
        date: '2026-02-15',
        commentaire:
          'Bonne pédagogie, cours bien structurés. Recommandé pour tous niveaux.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-034',
        nom: 'Cours de tennis individuel',
        sport: 'tennis',
        description:
          'Cours particulier de tennis : technique, tactique et jeu en situation.',
        tarifHeure: 50,
        dureeMinutes: 60,
        tags: ['competition', 'performance', 'bien_etre'],
        format: 'presentiel',
        actif: true,
        nbReservations: 58,
        caGenere: 2900,
      },
      {
        id: 'cs-035',
        nom: 'Prépa physique tennis',
        sport: 'fitness',
        description:
          'Préparation physique adaptée au tennis : explosivité, endurance et mobilité.',
        tarifHeure: 45,
        dureeMinutes: 60,
        tags: ['performance', 'cardio', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 22,
        caGenere: 990,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 45,
    tarifMax: 50,
    vibe: { pedagogieDiscipline: 5, suiviAutonomie: 6, dataRessenti: 5 },
  },
  {
    id: 'pro-025',
    prenom: 'Jean-Baptiste',
    nom: 'GIRARD',
    photo:
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&q=80',
    specialite: 'educateur_sportif',
    sports: ['natation', 'fitness'],
    bio: "Éducateur sportif passionné par le milieu aquatique depuis 15 ans. Ancien nageur de compétition, j'enseigne la natation à tous les âges et tous les niveaux. Je propose aussi des séances d'aquagym et de préparation physique aquatique.",
    anneesExperience: 15,
    formations: ['BPJEPS AAN', 'DEJEPS Natation', 'Certificat maître-nageur sauveteur'],
    ville: 'Paris 13e',
    codePostal: '75013',
    rayonKm: 12,
    formats: ['presentiel'],
    formule: 'standard',
    note: 4.6,
    nbAvis: 20,
    avis: [
      {
        id: 'avis-049',
        auteur: 'Virginie L.',
        note: 5,
        date: '2026-04-05',
        commentaire:
          "Jean-Baptiste m'a appris le papillon en 3 mois. Patience et technique au rendez-vous.",
      },
      {
        id: 'avis-050',
        auteur: 'Patrick N.',
        note: 4,
        date: '2026-03-14',
        commentaire:
          "Excellent pédagogue. Mon fils qui avait peur de l'eau nage maintenant 50m sans s'arrêter.",
      },
    ],
    cartesServices: [
      {
        id: 'cs-047',
        nom: 'Natation technique avancée',
        sport: 'natation',
        description:
          'Perfectionnement des 4 nages avec analyse vidéo et correction posturale.',
        tarifHeure: 50,
        dureeMinutes: 60,
        tags: ['performance', 'competition', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 55,
        caGenere: 2750,
      },
      {
        id: 'cs-048',
        nom: 'Apprentissage natation adulte',
        sport: 'natation',
        description:
          'Cours pour adultes débutants ou aquaphobes. Progression en douceur et confiance.',
        tarifHeure: 45,
        dureeMinutes: 45,
        tags: ['bien_etre', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 32,
        caGenere: 1440,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 45,
    tarifMax: 50,
    vibe: { pedagogieDiscipline: 4, suiviAutonomie: 3, dataRessenti: 6 },
  },
  {
    id: 'pro-033',
    prenom: 'Djibril',
    nom: 'KONATÉ',
    photo:
      'https://images.unsplash.com/photo-1583468982228-19f19164aee2?w=400&h=400&fit=crop&q=80',
    specialite: 'educateur_sportif',
    sports: ['football', 'fitness'],
    bio: "Éducateur sportif diplômé, passionné de football depuis toujours. J'interviens auprès des jeunes et des adultes pour transmettre les fondamentaux techniques et tactiques. Mes séances allient plaisir du jeu, discipline et préparation physique.",
    anneesExperience: 8,
    formations: ['BPJEPS Football', 'BPJEPS AF', 'CQP Animateur périscolaire'],
    ville: 'Bobigny',
    codePostal: '93000',
    rayonKm: 15,
    formats: ['presentiel'],
    formule: 'standard',
    note: 4.4,
    nbAvis: 11,
    avis: [
      {
        id: 'avis-065',
        auteur: 'Ryad M.',
        note: 5,
        date: '2026-03-30',
        commentaire:
          'Djibril est top avec les jeunes. Mon fils a intégré le pôle espoir grâce à son travail.',
      },
      {
        id: 'avis-066',
        auteur: 'Olivia P.',
        note: 4,
        date: '2026-02-25',
        commentaire: "Super éducateur, pédagogue et patient. Les enfants l'adorent.",
      },
    ],
    cartesServices: [
      {
        id: 'cs-062',
        nom: 'Coaching football jeunes',
        sport: 'football',
        description:
          'Entraînement individuel football pour jeunes joueurs : technique, coordination, tactique.',
        tarifHeure: 40,
        dureeMinutes: 75,
        tags: ['competition', 'performance', 'cardio'],
        format: 'presentiel',
        actif: true,
        nbReservations: 48,
        caGenere: 1920,
      },
      {
        id: 'cs-063',
        nom: 'Fitness football',
        sport: 'fitness',
        description: 'Préparation physique ludique inspirée des exercices de football.',
        tarifHeure: 35,
        dureeMinutes: 60,
        tags: ['cardio', 'renforcement', 'bien_etre'],
        format: 'presentiel',
        actif: true,
        nbReservations: 18,
        caGenere: 630,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 35,
    tarifMax: 40,
    vibe: { pedagogieDiscipline: 5, suiviAutonomie: 4, dataRessenti: 6 },
  },
  {
    id: 'pro-038',
    prenom: 'Lucie',
    nom: 'GAUTHIER',
    photo:
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=400&fit=crop&q=80',
    specialite: 'educateur_sportif',
    sports: ['tennis', 'fitness'],
    bio: "Éducatrice sportive diplômée, monitrice de tennis depuis 6 ans. Ma méthode ludique et progressive convient autant aux enfants qu'aux adultes. J'ajoute du fitness à mes cours pour développer les qualités physiques nécessaires au tennis.",
    anneesExperience: 6,
    formations: ['DEJEPS Tennis', 'BPJEPS AF', 'Formation premiers secours PSC1'],
    ville: 'Maisons-Laffitte',
    codePostal: '78600',
    rayonKm: 12,
    formats: ['presentiel'],
    formule: 'standard',
    note: 4.4,
    nbAvis: 9,
    avis: [
      {
        id: 'avis-075',
        auteur: 'Alain R.',
        note: 5,
        date: '2026-03-25',
        commentaire:
          'Lucie est une excellente prof de tennis. Mon fils progresse de manière incroyable.',
      },
      {
        id: 'avis-076',
        auteur: 'Claire T.',
        note: 4,
        date: '2026-02-20',
        commentaire:
          'Bonne pédagogie, cours bien structurés. Convient parfaitement aux débutants.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-072',
        nom: 'Tennis initiation',
        sport: 'tennis',
        description:
          'Cours de tennis pour débutants : prise en main, coups de base et jeu.',
        tarifHeure: 45,
        dureeMinutes: 60,
        tags: ['bien_etre', 'cardio'],
        format: 'presentiel',
        actif: true,
        nbReservations: 35,
        caGenere: 1575,
      },
      {
        id: 'cs-073',
        nom: 'Tennis perfectionnement',
        sport: 'tennis',
        description:
          'Travail technique avancé : service, volée, jeu de jambes et tactique.',
        tarifHeure: 50,
        dureeMinutes: 60,
        tags: ['competition', 'performance'],
        format: 'presentiel',
        actif: true,
        nbReservations: 22,
        caGenere: 1100,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire'],
    tarifMin: 45,
    tarifMax: 50,
    vibe: { pedagogieDiscipline: 3, suiviAutonomie: 5, dataRessenti: 6 },
  },
  {
    id: 'pro-045',
    prenom: 'Maxime',
    nom: 'BERNARD',
    photo:
      'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400&h=400&fit=crop&q=80',
    specialite: 'educateur_sportif',
    sports: ['natation', 'autre'],
    bio: "Éducateur sportif multisport avec une spécialisation natation et sauvetage aquatique. J'interviens auprès des collectivités et en privé pour des cours de natation, d'aquabiking et de triathlon. Mon mot d'ordre : sécurité et progression.",
    anneesExperience: 12,
    formations: ['BPJEPS AAN', 'BPJEPS APT', 'Brevet de surveillant de baignade'],
    ville: 'Colombes',
    codePostal: '92700',
    rayonKm: 12,
    formats: ['presentiel'],
    formule: 'standard',
    note: 4.5,
    nbAvis: 15,
    avis: [
      {
        id: 'avis-089',
        auteur: 'Christelle V.',
        note: 5,
        date: '2026-03-28',
        commentaire:
          'Maxime a appris à nager à ma fille de 5 ans en quelques séances. Patient et compétent.',
      },
      {
        id: 'avis-090',
        auteur: 'Arnaud J.',
        note: 4,
        date: '2026-03-05',
        commentaire:
          'Bon coaching pour préparer mon premier triathlon. La partie natation a été déterminante.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-087',
        nom: 'Natation enfants & adultes',
        sport: 'natation',
        description:
          "Cours de natation individuels ou en petit groupe. Du bébé nageur à l'adulte confirmé.",
        tarifHeure: 40,
        dureeMinutes: 45,
        tags: ['bien_etre', 'cardio'],
        format: 'presentiel',
        actif: true,
        nbReservations: 60,
        caGenere: 2400,
      },
      {
        id: 'cs-088',
        nom: 'Prépa triathlon natation',
        sport: 'autre',
        description:
          'Coaching natation spécifique triathlon : eau libre, orientation et transitions.',
        tarifHeure: 50,
        dureeMinutes: 60,
        tags: ['competition', 'performance', 'cardio'],
        format: 'presentiel',
        actif: true,
        nbReservations: 18,
        caGenere: 900,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 40,
    tarifMax: 50,
    vibe: { pedagogieDiscipline: 4, suiviAutonomie: 3, dataRessenti: 5 },
  },
];
