import type { Pro } from '@/types';

export const prosNutritionnistes: Pro[] = [
  {
    id: 'pro-008',
    prenom: 'Amina',
    nom: 'BENALI',
    photo:
      'https://images.unsplash.com/photo-1607962837359-5e7e89f86776?w=400&h=400&fit=crop&q=80',
    specialite: 'nutritionniste',
    sports: ['fitness'],
    bio: 'Nutritionniste du sport diplômée, je vous accompagne pour optimiser votre alimentation en fonction de vos objectifs sportifs. Fini les régimes restrictifs : je prône une alimentation plaisir, équilibrée et adaptée à votre mode de vie.',
    anneesExperience: 6,
    formations: [
      'Master Nutrition du sport',
      'DU Micronutrition',
      'Certification Precision Nutrition',
    ],
    ville: 'Paris 9e',
    codePostal: '75009',
    rayonKm: 15,
    formats: ['distanciel', 'hybride'],
    formule: 'premium',
    note: 4.8,
    nbAvis: 17,
    avis: [
      {
        id: 'avis-015',
        auteur: 'Sarah K.',
        note: 5,
        date: '2026-04-10',
        commentaire:
          'Amina a complètement changé ma relation à la nourriture. Je mange mieux et je performe mieux.',
      },
      {
        id: 'avis-016',
        auteur: 'David R.',
        note: 5,
        date: '2026-03-25',
        commentaire:
          'Enfin une nutritionniste qui ne met pas sur un régime ! Approche intelligente et personnalisée.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-014',
        nom: 'Bilan nutritionnel sportif',
        sport: 'fitness',
        description:
          'Bilan complet de vos habitudes alimentaires et plan personnalisé selon vos objectifs.',
        tarifHeure: 65,
        dureeMinutes: 90,
        tags: ['nutrition', 'perte_poids', 'performance'],
        format: 'hybride',
        actif: true,
        nbReservations: 52,
        caGenere: 3380,
      },
      {
        id: 'cs-015',
        nom: 'Suivi nutrition mensuel',
        sport: 'fitness',
        description:
          'Ajustements mensuels de votre plan alimentaire avec analyse de vos progrès.',
        tarifHeure: 55,
        dureeMinutes: 45,
        tags: ['nutrition', 'bien_etre'],
        format: 'distanciel',
        actif: true,
        nbReservations: 34,
        caGenere: 1870,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 55,
    tarifMax: 65,
    vibe: { pedagogieDiscipline: 3, suiviAutonomie: 4, dataRessenti: 7 },
  },
  {
    id: 'pro-018',
    prenom: 'Linh',
    nom: 'TRAN',
    photo:
      'https://images.unsplash.com/photo-1552196563-55cd4e45efb3?w=400&h=400&fit=crop&q=80',
    specialite: 'nutritionniste',
    sports: ['running', 'fitness'],
    bio: "Diététicienne du sport, je suis spécialisée dans la nutrition de l'endurance et la perte de poids santé. Mon approche est pragmatique : pas de super-aliments miracles, juste une alimentation intelligente adaptée à votre vie et vos entraînements.",
    anneesExperience: 8,
    formations: [
      'BTS Diététique',
      'DU Nutrition du sportif',
      'Certification Sport Nutrition',
    ],
    ville: 'Paris 3e',
    codePostal: '75003',
    rayonKm: 12,
    formats: ['distanciel', 'presentiel'],
    formule: 'premium',
    note: 4.7,
    nbAvis: 13,
    avis: [
      {
        id: 'avis-035',
        auteur: 'Benjamin F.',
        note: 5,
        date: '2026-04-03',
        commentaire:
          "Linh m'a aidé à optimiser ma nutrition pour le marathon. Plus d'énergie, moins de crampes.",
      },
      {
        id: 'avis-036',
        auteur: 'Marion D.',
        note: 4,
        date: '2026-03-15',
        commentaire:
          'Conseils concrets et réalistes. Pas de régime draconien, juste du bon sens adapté au sport.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-032',
        nom: 'Nutrition endurance',
        sport: 'running',
        description:
          "Plan alimentaire optimisé pour les sports d'endurance : marathon, trail, triathlon.",
        tarifHeure: 60,
        dureeMinutes: 60,
        tags: ['nutrition', 'performance', 'competition'],
        format: 'distanciel',
        actif: true,
        nbReservations: 36,
        caGenere: 2160,
      },
      {
        id: 'cs-033',
        nom: 'Rééquilibrage alimentaire',
        sport: 'fitness',
        description:
          'Programme de rééquilibrage alimentaire pour perdre du poids durablement.',
        tarifHeure: 55,
        dureeMinutes: 60,
        tags: ['nutrition', 'perte_poids', 'bien_etre'],
        format: 'presentiel',
        actif: true,
        nbReservations: 28,
        caGenere: 1540,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 55,
    tarifMax: 60,
    vibe: { pedagogieDiscipline: 4, suiviAutonomie: 5, dataRessenti: 4 },
  },
  {
    id: 'pro-024',
    prenom: 'Charlotte',
    nom: 'LEROY',
    photo:
      'https://images.unsplash.com/photo-1518459031867-a89b944bffe4?w=400&h=400&fit=crop&q=80',
    specialite: 'nutritionniste',
    sports: ['musculation', 'fitness'],
    bio: "Nutritionniste du sport spécialisée dans la prise de masse et la sèche. J'accompagne bodybuilders naturels et sportifs exigeants avec des plans alimentaires précis et adaptés à chaque phase d'entraînement. La nutrition est 80% de vos résultats.",
    anneesExperience: 7,
    formations: [
      'Master Nutrition',
      'DU Nutrition et performance sportive',
      'Certification ISSN',
    ],
    ville: 'Boulogne-Billancourt',
    codePostal: '92100',
    rayonKm: 12,
    formats: ['distanciel', 'hybride'],
    formule: 'premium',
    note: 4.6,
    nbAvis: 11,
    avis: [
      {
        id: 'avis-047',
        auteur: 'Mathieu B.',
        note: 5,
        date: '2026-04-02',
        commentaire:
          "Charlotte m'a fait un plan de sèche impeccable. -6% de body fat en 8 semaines.",
      },
      {
        id: 'avis-048',
        auteur: 'Sandrine V.',
        note: 4,
        date: '2026-03-10',
        commentaire:
          "Bons conseils, plans précis. Un peu cher mais les résultats justifient l'investissement.",
      },
    ],
    cartesServices: [
      {
        id: 'cs-045',
        nom: 'Plan nutrition prise de masse',
        sport: 'musculation',
        description:
          'Plan alimentaire optimisé pour la prise de masse musculaire avec supplémentation.',
        tarifHeure: 60,
        dureeMinutes: 60,
        tags: ['nutrition', 'prise_masse', 'performance'],
        format: 'distanciel',
        actif: true,
        nbReservations: 30,
        caGenere: 1800,
      },
      {
        id: 'cs-046',
        nom: 'Plan sèche & définition',
        sport: 'fitness',
        description:
          'Programme nutritionnel de sèche progressive pour atteindre votre physique objectif.',
        tarifHeure: 60,
        dureeMinutes: 60,
        tags: ['nutrition', 'perte_poids', 'performance'],
        format: 'hybride',
        actif: true,
        nbReservations: 25,
        caGenere: 1500,
      },
    ],
    niveauEnseigne: ['intermediaire', 'avance'],
    tarifMin: 60,
    tarifMax: 60,
    vibe: { pedagogieDiscipline: 6, suiviAutonomie: 5, dataRessenti: 3 },
  },
  {
    id: 'pro-036',
    prenom: 'Marie',
    nom: 'BONNET',
    photo:
      'https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=400&h=400&fit=crop&q=80',
    specialite: 'nutritionniste',
    sports: ['yoga', 'fitness'],
    bio: "Nutritionniste holistique, je crois en l'alimentation comme pilier de la santé globale. Mon approche intègre la nutrition, le bien-être digestif et la gestion du stress alimentaire. Pas de culpabilité, juste de la bienveillance et des résultats.",
    anneesExperience: 10,
    formations: [
      'Master Nutrition Santé',
      'DU Phytothérapie',
      'Certification Nutrithérapie fonctionnelle',
    ],
    ville: 'Paris 8e',
    codePostal: '75008',
    rayonKm: 15,
    formats: ['distanciel', 'presentiel'],
    formule: 'elite',
    note: 4.8,
    nbAvis: 19,
    avis: [
      {
        id: 'avis-071',
        auteur: 'Stéphanie G.',
        note: 5,
        date: '2026-04-09',
        commentaire:
          'Marie a résolu mes problèmes digestifs chroniques. Son approche globale est exceptionnelle.',
      },
      {
        id: 'avis-072',
        auteur: 'Philippe C.',
        note: 5,
        date: '2026-03-22',
        commentaire:
          "Enfin une nutritionniste qui prend le temps d'écouter. Plans sur mesure et résultats visibles.",
      },
    ],
    cartesServices: [
      {
        id: 'cs-068',
        nom: 'Bilan nutrition & bien-être',
        sport: 'fitness',
        description:
          'Bilan nutritionnel complet avec approche holistique : alimentation, sommeil, stress.',
        tarifHeure: 75,
        dureeMinutes: 90,
        tags: ['nutrition', 'bien_etre', 'perte_poids'],
        format: 'presentiel',
        actif: true,
        nbReservations: 45,
        caGenere: 3375,
      },
      {
        id: 'cs-069',
        nom: 'Nutrition yoga & détox',
        sport: 'yoga',
        description:
          'Plan alimentaire adapté à une pratique yogique : légèreté, énergie et détoxification.',
        tarifHeure: 65,
        dureeMinutes: 60,
        tags: ['nutrition', 'bien_etre', 'relaxation'],
        format: 'distanciel',
        actif: true,
        nbReservations: 22,
        caGenere: 1430,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 65,
    tarifMax: 75,
    vibe: { pedagogieDiscipline: 2, suiviAutonomie: 3, dataRessenti: 9 },
  },
  {
    id: 'pro-049',
    prenom: 'Aminata',
    nom: 'SOW',
    photo:
      'https://images.unsplash.com/photo-1571731956672-f2b94d7dd0d6?w=400&h=400&fit=crop&q=80',
    specialite: 'nutritionniste',
    sports: ['running', 'crossfit'],
    bio: "Nutritionniste du sport passionnée par la performance et la récupération. Ancienne athlète en course de fond, je connais les besoins nutritionnels des sportifs d'endurance et de haute intensité. Mon approche est basée sur la science et le plaisir de manger.",
    anneesExperience: 7,
    formations: [
      'Master Nutrition et sciences des aliments',
      'DU Nutrition du sportif',
      'Certification Examine.com',
    ],
    ville: 'Nogent-sur-Marne',
    codePostal: '94130',
    rayonKm: 12,
    formats: ['distanciel', 'hybride'],
    formule: 'premium',
    note: 4.6,
    nbAvis: 11,
    avis: [
      {
        id: 'avis-097',
        auteur: 'Étienne W.',
        note: 5,
        date: '2026-04-05',
        commentaire:
          "Aminata a optimisé ma nutrition pour le CrossFit. Plus d'énergie, meilleure récupération.",
      },
      {
        id: 'avis-098',
        auteur: 'Maryam B.',
        note: 4,
        date: '2026-03-18',
        commentaire:
          'Plans nutritionnels clairs et faciles à suivre. Résultats progressifs mais durables.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-095',
        nom: 'Nutrition haute intensité',
        sport: 'crossfit',
        description:
          'Plan alimentaire adapté aux sports haute intensité : timing, macros et récupération.',
        tarifHeure: 60,
        dureeMinutes: 60,
        tags: ['nutrition', 'performance', 'intensif'],
        format: 'distanciel',
        actif: true,
        nbReservations: 28,
        caGenere: 1680,
      },
      {
        id: 'cs-096',
        nom: 'Nutrition endurance & trail',
        sport: 'running',
        description:
          'Stratégie nutritionnelle pour courses longues : charge glucidique, ravitaillement, récupération.',
        tarifHeure: 55,
        dureeMinutes: 60,
        tags: ['nutrition', 'competition', 'performance'],
        format: 'hybride',
        actif: true,
        nbReservations: 22,
        caGenere: 1210,
      },
    ],
    niveauEnseigne: ['intermediaire', 'avance'],
    tarifMin: 55,
    tarifMax: 60,
    vibe: { pedagogieDiscipline: 5, suiviAutonomie: 5, dataRessenti: 4 },
  },
];
