import type { Pro } from '@/types';

export const prosPrepMental: Pro[] = [
  {
    id: 'pro-010',
    prenom: 'Nathalie',
    nom: 'PETIT',
    photo:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&q=80',
    specialite: 'preparateur_mental',
    sports: ['tennis', 'running'],
    bio: "Préparatrice mentale certifiée, j'accompagne les sportifs dans la gestion du stress compétitif, la concentration et la confiance en soi. Mon approche mêle sophrologie, visualisation et PNL. Chaque mental est un terrain de jeu unique.",
    anneesExperience: 11,
    formations: [
      'Master Psychologie du sport',
      'DU Préparation mentale',
      'Certification sophrologie sportive',
    ],
    ville: 'Neuilly-sur-Seine',
    codePostal: '92200',
    rayonKm: 12,
    formats: ['presentiel', 'distanciel'],
    formule: 'elite',
    note: 4.9,
    nbAvis: 15,
    avis: [
      {
        id: 'avis-019',
        auteur: 'Alexandre F.',
        note: 5,
        date: '2026-04-12',
        commentaire:
          "Nathalie m'a aidé à gérer mon stress en compétition. Mon classement tennis a bondi de 2 séries.",
      },
      {
        id: 'avis-020',
        auteur: 'Pauline C.',
        note: 5,
        date: '2026-03-28',
        commentaire:
          'Transformateur. Je ne craque plus en fin de course, mon mental est devenu mon meilleur allié.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-017',
        nom: 'Prépa mentale compétition',
        sport: 'tennis',
        description:
          'Programme de préparation mentale pour compétiteurs : gestion du stress, focus et confiance.',
        tarifHeure: 80,
        dureeMinutes: 60,
        tags: ['competition', 'performance', 'bien_etre'],
        format: 'presentiel',
        actif: true,
        nbReservations: 38,
        caGenere: 3040,
      },
      {
        id: 'cs-018',
        nom: 'Coaching mental running',
        sport: 'running',
        description:
          'Techniques de visualisation et gestion de la douleur pour coureurs longue distance.',
        tarifHeure: 75,
        dureeMinutes: 60,
        tags: ['performance', 'bien_etre', 'competition'],
        format: 'distanciel',
        actif: true,
        nbReservations: 21,
        caGenere: 1575,
      },
    ],
    niveauEnseigne: ['intermediaire', 'avance'],
    tarifMin: 75,
    tarifMax: 80,
    vibe: { pedagogieDiscipline: 3, suiviAutonomie: 3, dataRessenti: 9 },
  },
  {
    id: 'pro-022',
    prenom: 'Mei',
    nom: 'WONG',
    photo:
      'https://images.unsplash.com/photo-1506863530036-1efeddceb993?w=400&h=400&fit=crop&q=80',
    specialite: 'preparateur_mental',
    sports: ['yoga', 'natation'],
    bio: "Préparatrice mentale et professeure de yoga thérapeutique. Mon approche intègre la méditation de pleine conscience, la respiration et la gestion émotionnelle. J'aide les sportifs à développer leur résilience mentale et leur concentration.",
    anneesExperience: 9,
    formations: ['Master Psychologie', 'RYT-500 Yoga Alliance', 'Certification MBSR'],
    ville: 'Paris 6e',
    codePostal: '75006',
    rayonKm: 10,
    formats: ['presentiel', 'distanciel', 'hybride'],
    formule: 'premium',
    note: 4.8,
    nbAvis: 12,
    avis: [
      {
        id: 'avis-043',
        auteur: 'Hélène B.',
        note: 5,
        date: '2026-04-08',
        commentaire:
          "Mei a changé ma vie. Sa méthode de méditation m'a permis de gérer mon anxiété en compétition.",
      },
      {
        id: 'avis-044',
        auteur: 'Florent M.',
        note: 5,
        date: '2026-03-12',
        commentaire:
          'Approche unique mêlant yoga et coaching mental. Très professionnel et apaisant.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-041',
        nom: 'Yoga thérapeutique & mental',
        sport: 'yoga',
        description:
          'Séances de yoga orientées gestion du stress et renforcement mental.',
        tarifHeure: 65,
        dureeMinutes: 60,
        tags: ['bien_etre', 'relaxation', 'performance'],
        format: 'hybride',
        actif: true,
        nbReservations: 42,
        caGenere: 2730,
      },
      {
        id: 'cs-042',
        nom: 'Coaching mental aquatique',
        sport: 'natation',
        description:
          'Techniques de respiration et concentration appliquées en milieu aquatique.',
        tarifHeure: 70,
        dureeMinutes: 60,
        tags: ['bien_etre', 'relaxation', 'performance'],
        format: 'presentiel',
        actif: true,
        nbReservations: 15,
        caGenere: 1050,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 65,
    tarifMax: 70,
    vibe: { pedagogieDiscipline: 1, suiviAutonomie: 4, dataRessenti: 10 },
  },
  {
    id: 'pro-030',
    prenom: 'Pierre',
    nom: 'VASSEUR',
    photo:
      'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400&h=400&fit=crop&q=80',
    specialite: 'preparateur_mental',
    sports: ['running', 'crossfit'],
    bio: "Préparateur mental et coach en performance. Ancien sportif de haut niveau en athlétisme, je connais la pression de la compétition. J'aide les athlètes à transformer leur stress en carburant. Méthode basée sur la visualisation et l'auto-dialogue.",
    anneesExperience: 12,
    formations: [
      'Master Psychologie du sport',
      'Certification coaching PNL',
      'DU Préparation mentale INSEP',
    ],
    ville: 'Paris 7e',
    codePostal: '75007',
    rayonKm: 15,
    formats: ['presentiel', 'distanciel'],
    formule: 'elite',
    note: 4.9,
    nbAvis: 17,
    avis: [
      {
        id: 'avis-059',
        auteur: 'Caroline F.',
        note: 5,
        date: '2026-04-11',
        commentaire:
          "Pierre m'a donné les clés mentales pour passer sous les 3h au marathon. Exceptionnel.",
      },
      {
        id: 'avis-060',
        auteur: 'Xavier D.',
        note: 5,
        date: '2026-03-25',
        commentaire:
          'Le meilleur investissement de ma carrière sportive. Mon mental est devenu mon arme secrète.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-056',
        nom: 'Coaching mental haute performance',
        sport: 'running',
        description:
          "Programme de préparation mentale pour athlètes d'endurance visant la haute performance.",
        tarifHeure: 85,
        dureeMinutes: 60,
        tags: ['competition', 'performance'],
        format: 'presentiel',
        actif: true,
        nbReservations: 40,
        caGenere: 3400,
      },
      {
        id: 'cs-057',
        nom: 'Gestion du stress compétitif',
        sport: 'crossfit',
        description:
          'Techniques de gestion du stress et de la pression en compétition CrossFit.',
        tarifHeure: 80,
        dureeMinutes: 60,
        tags: ['competition', 'performance', 'bien_etre'],
        format: 'distanciel',
        actif: true,
        nbReservations: 25,
        caGenere: 2000,
      },
    ],
    niveauEnseigne: ['intermediaire', 'avance'],
    tarifMin: 80,
    tarifMax: 85,
    vibe: { pedagogieDiscipline: 5, suiviAutonomie: 3, dataRessenti: 8 },
  },
  {
    id: 'pro-040',
    prenom: 'Alice',
    nom: 'LECLERC',
    photo:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&q=80',
    specialite: 'preparateur_mental',
    sports: ['natation', 'fitness'],
    bio: "Préparatrice mentale et sophrologue du sport. Mon travail se concentre sur la gestion de l'anxiété, la confiance en soi et la visualisation positive. J'interviens auprès de nageurs compétiteurs et de sportifs souhaitant débloquer leur potentiel mental.",
    anneesExperience: 8,
    formations: [
      'Master Psychologie du sport',
      'Diplôme de sophrologie RNCP',
      'Certification hypnose sportive',
    ],
    ville: 'Saint-Cloud',
    codePostal: '92210',
    rayonKm: 12,
    formats: ['presentiel', 'distanciel'],
    formule: 'premium',
    note: 4.7,
    nbAvis: 11,
    avis: [
      {
        id: 'avis-079',
        auteur: 'Élise P.',
        note: 5,
        date: '2026-04-05',
        commentaire:
          "Alice m'a aidée à vaincre ma peur de la compétition en natation. Résultats immédiats.",
      },
      {
        id: 'avis-080',
        auteur: 'Vincent L.',
        note: 4,
        date: '2026-03-18',
        commentaire:
          'Approche très douce et efficace. Les séances de visualisation sont bluffantes.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-077',
        nom: 'Sophrologie sportive',
        sport: 'natation',
        description:
          'Séances de sophrologie adaptées aux nageurs : gestion du stress et visualisation.',
        tarifHeure: 70,
        dureeMinutes: 60,
        tags: ['bien_etre', 'relaxation', 'competition'],
        format: 'presentiel',
        actif: true,
        nbReservations: 30,
        caGenere: 2100,
      },
      {
        id: 'cs-078',
        nom: 'Coaching confiance en soi',
        sport: 'fitness',
        description:
          'Programme de renforcement de la confiance en soi par le sport et le mental.',
        tarifHeure: 65,
        dureeMinutes: 60,
        tags: ['bien_etre', 'performance'],
        format: 'distanciel',
        actif: true,
        nbReservations: 18,
        caGenere: 1170,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 65,
    tarifMax: 70,
    vibe: { pedagogieDiscipline: 2, suiviAutonomie: 3, dataRessenti: 10 },
  },
  {
    id: 'pro-047',
    prenom: 'Émeline',
    nom: 'LEFÈVRE',
    photo:
      'https://images.unsplash.com/photo-1518459031867-a89b944bffe4?w=400&h=400&fit=crop&q=80',
    specialite: 'preparateur_mental',
    sports: ['tennis', 'yoga'],
    bio: 'Psychologue du sport et préparatrice mentale. Je travaille avec des tennismen et des sportifs de raquette pour optimiser leur concentration en match. Ma méthode intègre le yoga comme outil de gestion du stress et de pleine conscience.',
    anneesExperience: 10,
    formations: [
      'Doctorat Psychologie du sport',
      'RYT-200 Yoga Alliance',
      'Certification EMDR sport',
    ],
    ville: 'Le Chesnay',
    codePostal: '78150',
    rayonKm: 15,
    formats: ['presentiel', 'distanciel'],
    formule: 'elite',
    note: 4.9,
    nbAvis: 13,
    avis: [
      {
        id: 'avis-093',
        auteur: 'Thomas K.',
        note: 5,
        date: '2026-04-12',
        commentaire:
          "Émeline est brillante. Son travail sur ma concentration m'a fait gagner 3 classements en tennis.",
      },
      {
        id: 'avis-094',
        auteur: 'Julie M.',
        note: 5,
        date: '2026-03-25',
        commentaire:
          'La combinaison yoga et coaching mental est puissante. Résultats visibles dès les premières séances.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-091',
        nom: 'Prépa mentale tennis',
        sport: 'tennis',
        description:
          'Programme de coaching mental spécifique tennis : concentration, gestion de la frustration, routine.',
        tarifHeure: 85,
        dureeMinutes: 60,
        tags: ['competition', 'performance', 'bien_etre'],
        format: 'presentiel',
        actif: true,
        nbReservations: 32,
        caGenere: 2720,
      },
      {
        id: 'cs-092',
        nom: 'Yoga & pleine conscience sport',
        sport: 'yoga',
        description:
          'Séances de yoga et méditation orientées performance sportive et gestion du stress.',
        tarifHeure: 75,
        dureeMinutes: 60,
        tags: ['relaxation', 'bien_etre', 'performance'],
        format: 'distanciel',
        actif: true,
        nbReservations: 20,
        caGenere: 1500,
      },
    ],
    niveauEnseigne: ['intermediaire', 'avance'],
    tarifMin: 75,
    tarifMax: 85,
    vibe: { pedagogieDiscipline: 3, suiviAutonomie: 4, dataRessenti: 9 },
  },
];
