import type { Pro } from '@/types';

export const prosPrepPhysique: Pro[] = [
  {
    id: 'pro-002',
    prenom: 'Youssef',
    nom: 'AMRANI',
    photo:
      'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=400&h=400&fit=crop&q=80',
    specialite: 'preparateur_physique',
    sports: ['crossfit', 'musculation', 'running'],
    bio: 'Ancien athlète de haut niveau reconverti en préparateur physique. Je forme des sportifs ambitieux qui veulent repousser leurs limites. Approche data-driven avec suivi de toutes les métriques.',
    anneesExperience: 12,
    formations: ['Master STAPS', 'CrossFit L3', 'Certification VO2max'],
    ville: 'Boulogne-Billancourt',
    codePostal: '92100',
    rayonKm: 15,
    formats: ['presentiel'],
    formule: 'elite',
    note: 4.9,
    nbAvis: 21,
    avis: [
      {
        id: 'avis-004',
        auteur: 'Lucas R.',
        note: 5,
        date: '2026-04-05',
        commentaire:
          "Youssef m'a préparé pour mon premier semi-marathon. Résultat : 1h38. Incroyable.",
      },
      {
        id: 'avis-005',
        auteur: 'Camille D.',
        note: 5,
        date: '2026-03-20',
        commentaire:
          "Le meilleur coach que j'ai eu. Exigeant mais juste. On progresse à chaque séance.",
      },
    ],
    cartesServices: [
      {
        id: 'cs-003',
        nom: 'Prépa physique complète',
        sport: 'crossfit',
        description:
          'Programme CrossFit sur mesure avec suivi de progression et benchmark réguliers.',
        tarifHeure: 75,
        dureeMinutes: 90,
        tags: ['competition', 'performance', 'intensif', 'cardio'],
        format: 'presentiel',
        actif: true,
        nbReservations: 63,
        caGenere: 4725,
      },
      {
        id: 'cs-004',
        nom: 'Running performance',
        sport: 'running',
        description:
          "Plans d'entraînement course à pied avec séances encadrées et analyse foulée.",
        tarifHeure: 65,
        dureeMinutes: 75,
        tags: ['competition', 'cardio', 'performance'],
        format: 'presentiel',
        actif: true,
        nbReservations: 28,
        caGenere: 1820,
      },
    ],
    niveauEnseigne: ['intermediaire', 'avance'],
    tarifMin: 65,
    tarifMax: 75,
    vibe: { pedagogieDiscipline: 8, suiviAutonomie: 6, dataRessenti: 2 },
  },
  {
    id: 'pro-005',
    prenom: 'Julie',
    nom: 'MARTIN',
    photo:
      'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=400&fit=crop&q=80',
    specialite: 'preparateur_physique',
    sports: ['fitness', 'running', 'musculation'],
    bio: "Préparatrice physique passionnée par la science de l'entraînement. Je conçois des programmes basés sur les dernières études, avec un suivi data précis. Mon objectif : des résultats mesurables et durables pour chacun de mes athlètes.",
    anneesExperience: 9,
    formations: ['Master STAPS', 'Certification NSCA-CSCS', 'DU Nutrition du sportif'],
    ville: 'Paris 16e',
    codePostal: '75016',
    rayonKm: 15,
    formats: ['presentiel', 'distanciel', 'hybride'],
    formule: 'elite',
    note: 4.8,
    nbAvis: 16,
    avis: [
      {
        id: 'avis-009',
        auteur: 'Marc T.',
        note: 5,
        date: '2026-04-08',
        commentaire:
          "Julie est la meilleure investissement santé que j'ai fait. Résultats bluffants en 2 mois.",
      },
      {
        id: 'avis-010',
        auteur: 'Inès B.',
        note: 4,
        date: '2026-03-18',
        commentaire:
          'Très pro, suivi data impressionnant. Parfois un peu trop de données pour moi mais les résultats parlent.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-007',
        nom: 'Programme perte de poids',
        sport: 'fitness',
        description:
          'Programme scientifique de perte de poids avec nutrition et entraînement combinés.',
        tarifHeure: 70,
        dureeMinutes: 60,
        tags: ['perte_poids', 'nutrition', 'cardio', 'renforcement'],
        format: 'hybride',
        actif: true,
        nbReservations: 41,
        caGenere: 2870,
      },
      {
        id: 'cs-008',
        nom: 'Prépa running 10K-Semi',
        sport: 'running',
        description:
          "Plan d'entraînement running personnalisé avec séances encadrées et analyse données.",
        tarifHeure: 65,
        dureeMinutes: 75,
        tags: ['competition', 'performance', 'cardio'],
        format: 'presentiel',
        actif: true,
        nbReservations: 22,
        caGenere: 1430,
      },
      {
        id: 'cs-009',
        nom: 'Musculation & force',
        sport: 'musculation',
        description:
          'Programme de force et hypertrophie avec périodisation et suivi des charges.',
        tarifHeure: 70,
        dureeMinutes: 75,
        tags: ['prise_masse', 'musculation', 'performance'],
        format: 'presentiel',
        actif: true,
        nbReservations: 18,
        caGenere: 1260,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 65,
    tarifMax: 70,
    vibe: { pedagogieDiscipline: 5, suiviAutonomie: 4, dataRessenti: 2 },
  },
  {
    id: 'pro-007',
    prenom: 'Rémi',
    nom: 'NGUYEN',
    photo:
      'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&h=400&fit=crop&q=80',
    specialite: 'preparateur_physique',
    sports: ['musculation', 'crossfit'],
    bio: 'Préparateur physique certifié avec une approche centrée sur la performance fonctionnelle. Ancien compétiteur en haltérophilie, je mets mon expertise au service de sportifs de tous niveaux. La rigueur et la progression sont mes maîtres mots.',
    anneesExperience: 7,
    formations: ['Licence STAPS', 'CrossFit L2', 'Certification Westside Barbell'],
    ville: 'Levallois-Perret',
    codePostal: '92300',
    rayonKm: 12,
    formats: ['presentiel'],
    formule: 'premium',
    note: 4.7,
    nbAvis: 13,
    avis: [
      {
        id: 'avis-013',
        auteur: 'Antoine D.',
        note: 5,
        date: '2026-04-02',
        commentaire:
          'Rémi connaît son sujet sur le bout des doigts. Mon squat a pris 30 kg en 4 mois grâce à lui.',
      },
      {
        id: 'avis-014',
        auteur: 'Margaux S.',
        note: 4,
        date: '2026-03-08',
        commentaire:
          'Très technique dans ses explications. Parfait pour progresser en force.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-012',
        nom: 'Force & hypertrophie',
        sport: 'musculation',
        description:
          'Programme de musculation structuré avec périodisation et suivi des charges.',
        tarifHeure: 60,
        dureeMinutes: 75,
        tags: ['prise_masse', 'musculation', 'performance'],
        format: 'presentiel',
        actif: true,
        nbReservations: 45,
        caGenere: 2700,
      },
      {
        id: 'cs-013',
        nom: 'CrossFit encadré',
        sport: 'crossfit',
        description: 'WODs personnalisés et travail technique des mouvements olympiques.',
        tarifHeure: 55,
        dureeMinutes: 60,
        tags: ['intensif', 'performance', 'cardio'],
        format: 'presentiel',
        actif: true,
        nbReservations: 30,
        caGenere: 1650,
      },
    ],
    niveauEnseigne: ['intermediaire', 'avance'],
    tarifMin: 55,
    tarifMax: 60,
    vibe: { pedagogieDiscipline: 7, suiviAutonomie: 5, dataRessenti: 3 },
  },
  {
    id: 'pro-013',
    prenom: 'Karim',
    nom: 'ZIDANE',
    photo:
      'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=400&h=400&fit=crop&q=80',
    specialite: 'preparateur_physique',
    sports: ['boxe', 'crossfit', 'musculation'],
    bio: "Préparateur physique orienté sports de combat. Je prépare des boxeurs, des pratiquants de MMA et des crossfiteurs pour la compétition. Mon approche est basée sur la science de l'entraînement avec une touche old school. Pas de raccourcis.",
    anneesExperience: 14,
    formations: ['Master STAPS', 'DEJEPS Boxe', 'Certification Strength & Conditioning'],
    ville: 'Nanterre',
    codePostal: '92000',
    rayonKm: 15,
    formats: ['presentiel'],
    formule: 'elite',
    note: 4.8,
    nbAvis: 19,
    avis: [
      {
        id: 'avis-025',
        auteur: 'Sofiane A.',
        note: 5,
        date: '2026-04-08',
        commentaire:
          "Karim est une machine. Sa prépa m'a permis de gagner mon premier combat amateur.",
      },
      {
        id: 'avis-026',
        auteur: 'Valentin R.',
        note: 5,
        date: '2026-03-22',
        commentaire:
          'Exigeant mais les résultats sont là. On ne rigole pas mais on progresse comme nulle part ailleurs.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-023',
        nom: 'Prépa physique combat',
        sport: 'boxe',
        description: 'Programme de préparation physique spécifique aux sports de combat.',
        tarifHeure: 80,
        dureeMinutes: 90,
        tags: ['competition', 'performance', 'intensif', 'cardio'],
        format: 'presentiel',
        actif: true,
        nbReservations: 55,
        caGenere: 4400,
      },
      {
        id: 'cs-024',
        nom: 'CrossFit performance',
        sport: 'crossfit',
        description:
          'Programmation CrossFit avancée pour compétiteurs et passionnés exigeants.',
        tarifHeure: 75,
        dureeMinutes: 75,
        tags: ['intensif', 'performance', 'competition'],
        format: 'presentiel',
        actif: true,
        nbReservations: 38,
        caGenere: 2850,
      },
    ],
    niveauEnseigne: ['intermediaire', 'avance'],
    tarifMin: 75,
    tarifMax: 80,
    vibe: { pedagogieDiscipline: 10, suiviAutonomie: 7, dataRessenti: 2 },
  },
  {
    id: 'pro-021',
    prenom: 'Sébastien',
    nom: 'ROUX',
    photo:
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&h=400&fit=crop&q=80',
    specialite: 'preparateur_physique',
    sports: ['football', 'running', 'fitness'],
    bio: "Préparateur physique avec 13 ans d'expérience dans le sport de haut niveau. J'ai travaillé avec des clubs de football et des athlètes pros. Aujourd'hui je mets cette expertise au service de sportifs amateurs ambitieux.",
    anneesExperience: 13,
    formations: ['Master STAPS entraînement', 'DEJEPS', 'Certification GPS performance'],
    ville: 'Paris 14e',
    codePostal: '75014',
    rayonKm: 15,
    formats: ['presentiel', 'hybride'],
    formule: 'elite',
    note: 4.8,
    nbAvis: 18,
    avis: [
      {
        id: 'avis-041',
        auteur: 'Guillaume K.',
        note: 5,
        date: '2026-04-12',
        commentaire:
          "Sébastien a un niveau d'expertise rare. Mes perfs en course ont explosé en quelques mois.",
      },
      {
        id: 'avis-042',
        auteur: 'Amandine R.',
        note: 5,
        date: '2026-03-28',
        commentaire:
          'Prépa physique de qualité pro. Suivi rigoureux et programmes ultra détaillés.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-038',
        nom: 'Prépa physique football',
        sport: 'football',
        description:
          'Programme de préparation physique spécifique football : vitesse, endurance, explosivité.',
        tarifHeure: 75,
        dureeMinutes: 90,
        tags: ['competition', 'performance', 'intensif'],
        format: 'presentiel',
        actif: true,
        nbReservations: 40,
        caGenere: 3000,
      },
      {
        id: 'cs-039',
        nom: 'Prépa running avancée',
        sport: 'running',
        description:
          "Plan d'entraînement running avec analyse VO2max et séances sur piste.",
        tarifHeure: 70,
        dureeMinutes: 75,
        tags: ['competition', 'cardio', 'performance'],
        format: 'hybride',
        actif: true,
        nbReservations: 25,
        caGenere: 1750,
      },
      {
        id: 'cs-040',
        nom: 'Remise en forme athlétique',
        sport: 'fitness',
        description: 'Programme fitness intensif pour retrouver un niveau athlétique.',
        tarifHeure: 65,
        dureeMinutes: 60,
        tags: ['renforcement', 'cardio', 'intensif'],
        format: 'presentiel',
        actif: true,
        nbReservations: 18,
        caGenere: 1170,
      },
    ],
    niveauEnseigne: ['intermediaire', 'avance'],
    tarifMin: 65,
    tarifMax: 75,
    vibe: { pedagogieDiscipline: 8, suiviAutonomie: 5, dataRessenti: 2 },
  },
  {
    id: 'pro-028',
    prenom: 'Adrien',
    nom: 'MERCIER',
    photo:
      'https://images.unsplash.com/photo-1550345332-09e3ac987658?w=400&h=400&fit=crop&q=80',
    specialite: 'preparateur_physique',
    sports: ['tennis', 'fitness', 'running'],
    bio: "Préparateur physique certifié, je travaille avec des tennismen et des sportifs d'endurance. Mon approche est basée sur la prévention des blessures et l'optimisation de la performance. J'utilise les dernières technologies de suivi.",
    anneesExperience: 10,
    formations: ['Master STAPS', 'Certification NSCA-CPT', 'DU Prévention des blessures'],
    ville: 'Rueil-Malmaison',
    codePostal: '92500',
    rayonKm: 15,
    formats: ['presentiel', 'hybride'],
    formule: 'elite',
    note: 4.7,
    nbAvis: 14,
    avis: [
      {
        id: 'avis-055',
        auteur: 'Laurent V.',
        note: 5,
        date: '2026-04-06',
        commentaire:
          "Adrien est méticuleux. Grâce à son travail de prévention, je n'ai plus de blessures au tennis.",
      },
      {
        id: 'avis-056',
        auteur: 'Sophie R.',
        note: 4,
        date: '2026-03-20',
        commentaire:
          'Très bon préparateur, approche scientifique solide. Un peu froid dans le relationnel.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-052',
        nom: 'Prépa physique tennis',
        sport: 'tennis',
        description:
          'Préparation physique spécifique tennis : vitesse latérale, explosivité, endurance.',
        tarifHeure: 70,
        dureeMinutes: 75,
        tags: ['performance', 'competition', 'renforcement'],
        format: 'presentiel',
        actif: true,
        nbReservations: 35,
        caGenere: 2450,
      },
      {
        id: 'cs-053',
        nom: 'Prévention blessures & mobilité',
        sport: 'fitness',
        description:
          'Programme de mobilité et renforcement pour prévenir les blessures sportives.',
        tarifHeure: 65,
        dureeMinutes: 60,
        tags: ['mobilite', 'renforcement', 'bien_etre'],
        format: 'hybride',
        actif: true,
        nbReservations: 22,
        caGenere: 1430,
      },
    ],
    niveauEnseigne: ['intermediaire', 'avance'],
    tarifMin: 65,
    tarifMax: 70,
    vibe: { pedagogieDiscipline: 6, suiviAutonomie: 6, dataRessenti: 2 },
  },
  {
    id: 'pro-032',
    prenom: 'Nicolas',
    nom: 'BLANC',
    photo:
      'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=400&h=400&fit=crop&q=80',
    specialite: 'preparateur_physique',
    sports: ['running', 'fitness'],
    bio: "Préparateur physique spécialisé en course à pied et remise en forme. Ma méthode repose sur la progressivité et l'écoute du corps. Diplômé STAPS et certifié en analyse de foulée, je propose un accompagnement scientifique et humain.",
    anneesExperience: 8,
    formations: [
      'Licence STAPS',
      'Certification analyse de foulée',
      "DU Physiologie de l'exercice",
    ],
    ville: 'Clamart',
    codePostal: '92140',
    rayonKm: 12,
    formats: ['presentiel', 'distanciel'],
    formule: 'premium',
    note: 4.6,
    nbAvis: 12,
    avis: [
      {
        id: 'avis-063',
        auteur: 'Christophe M.',
        note: 5,
        date: '2026-04-02',
        commentaire:
          "Nicolas m'a corrigé ma foulée et mes douleurs aux genoux ont disparu. Compétent et sympa.",
      },
      {
        id: 'avis-064',
        auteur: 'Éloïse T.',
        note: 4,
        date: '2026-03-12',
        commentaire:
          "Bon suivi, bons plans d'entraînement. Approche très scientifique que j'apprécie.",
      },
    ],
    cartesServices: [
      {
        id: 'cs-060',
        nom: 'Analyse foulée & optimisation',
        sport: 'running',
        description:
          'Analyse biomécanique de votre foulée avec programme correctif personnalisé.',
        tarifHeure: 60,
        dureeMinutes: 75,
        tags: ['performance', 'mobilite', 'competition'],
        format: 'presentiel',
        actif: true,
        nbReservations: 28,
        caGenere: 1680,
      },
      {
        id: 'cs-061',
        nom: 'Remise en forme progressive',
        sport: 'fitness',
        description:
          "Programme de remise en forme basé sur la science de l'entraînement.",
        tarifHeure: 55,
        dureeMinutes: 60,
        tags: ['renforcement', 'cardio', 'bien_etre'],
        format: 'distanciel',
        actif: true,
        nbReservations: 20,
        caGenere: 1100,
      },
    ],
    niveauEnseigne: ['debutant', 'intermediaire', 'avance'],
    tarifMin: 55,
    tarifMax: 60,
    vibe: { pedagogieDiscipline: 4, suiviAutonomie: 4, dataRessenti: 3 },
  },
  {
    id: 'pro-039',
    prenom: 'Omar',
    nom: 'BENSAÏD',
    photo:
      'https://images.unsplash.com/photo-1549476464-37392f717541?w=400&h=400&fit=crop&q=80',
    specialite: 'preparateur_physique',
    sports: ['boxe', 'musculation', 'fitness'],
    bio: "Préparateur physique spécialiste de la performance athlétique. Ancien pratiquant de boxe thaï, j'ai développé une méthode qui combine force, explosivité et endurance. Je travaille aussi bien avec des compétiteurs qu'avec des sportifs loisir.",
    anneesExperience: 9,
    formations: [
      'Master STAPS Entraînement sportif',
      'Certification CSCS',
      'CrossFit L2',
    ],
    ville: 'Vitry-sur-Seine',
    codePostal: '94400',
    rayonKm: 15,
    formats: ['presentiel', 'hybride'],
    formule: 'premium',
    note: 4.7,
    nbAvis: 15,
    avis: [
      {
        id: 'avis-077',
        auteur: 'Nathan G.',
        note: 5,
        date: '2026-04-10',
        commentaire:
          "Omar m'a transformé physiquement en 6 mois. Sa méthode est brutalement efficace.",
      },
      {
        id: 'avis-078',
        auteur: 'Léa D.',
        note: 4,
        date: '2026-03-14',
        commentaire: 'Très bon préparateur physique. Séances intenses mais bien dosées.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-074',
        nom: 'Prépa physique athlétique',
        sport: 'musculation',
        description:
          'Programme de préparation physique générale orienté performance et explosivité.',
        tarifHeure: 65,
        dureeMinutes: 75,
        tags: ['performance', 'intensif', 'musculation'],
        format: 'presentiel',
        actif: true,
        nbReservations: 42,
        caGenere: 2730,
      },
      {
        id: 'cs-075',
        nom: 'Prépa combat spécifique',
        sport: 'boxe',
        description:
          'Préparation physique ciblée pour les sports de combat : explosivité et cardio.',
        tarifHeure: 60,
        dureeMinutes: 60,
        tags: ['competition', 'intensif', 'cardio'],
        format: 'presentiel',
        actif: true,
        nbReservations: 28,
        caGenere: 1680,
      },
      {
        id: 'cs-076',
        nom: 'Remise en forme intensive',
        sport: 'fitness',
        description:
          'Programme de remise en forme rapide et efficace pour sportifs motivés.',
        tarifHeure: 55,
        dureeMinutes: 60,
        tags: ['perte_poids', 'cardio', 'renforcement'],
        format: 'hybride',
        actif: true,
        nbReservations: 18,
        caGenere: 990,
      },
    ],
    niveauEnseigne: ['intermediaire', 'avance'],
    tarifMin: 55,
    tarifMax: 65,
    vibe: { pedagogieDiscipline: 8, suiviAutonomie: 6, dataRessenti: 3 },
  },
  {
    id: 'pro-043',
    prenom: 'Thibault',
    nom: 'PERRIN',
    photo:
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=400&fit=crop&q=80',
    specialite: 'preparateur_physique',
    sports: ['football', 'crossfit', 'musculation'],
    bio: "Préparateur physique diplômé avec 11 ans d'expérience dans le football professionnel. J'ai travaillé en Ligue 2 et en National. Ma méthode est basée sur la periodisation et le suivi GPS. Je propose désormais mes services aux sportifs amateurs exigeants.",
    anneesExperience: 11,
    formations: ['Master STAPS EOPS', 'DEJEPS Football', 'Certification Catapult GPS'],
    ville: 'Suresnes',
    codePostal: '92150',
    rayonKm: 15,
    formats: ['presentiel'],
    formule: 'elite',
    note: 4.8,
    nbAvis: 14,
    avis: [
      {
        id: 'avis-085',
        auteur: 'Jérémy F.',
        note: 5,
        date: '2026-04-08',
        commentaire:
          "Thibault a un niveau d'expertise incroyable. Prépa physique de qualité professionnelle.",
      },
      {
        id: 'avis-086',
        auteur: 'Clément R.',
        note: 5,
        date: '2026-03-22',
        commentaire:
          'Ex-prépa de L2, ça se voit. Méthode rigoureuse et suivi impeccable.',
      },
    ],
    cartesServices: [
      {
        id: 'cs-083',
        nom: 'Prépa physique football pro',
        sport: 'football',
        description:
          'Programme de préparation physique niveau professionnel avec suivi GPS et data.',
        tarifHeure: 85,
        dureeMinutes: 90,
        tags: ['competition', 'performance', 'intensif'],
        format: 'presentiel',
        actif: true,
        nbReservations: 30,
        caGenere: 2550,
      },
      {
        id: 'cs-084',
        nom: 'Force & puissance',
        sport: 'musculation',
        description:
          'Programme de développement de la force maximale et de la puissance musculaire.',
        tarifHeure: 75,
        dureeMinutes: 75,
        tags: ['musculation', 'performance', 'intensif'],
        format: 'presentiel',
        actif: true,
        nbReservations: 22,
        caGenere: 1650,
      },
    ],
    niveauEnseigne: ['intermediaire', 'avance'],
    tarifMin: 75,
    tarifMax: 85,
    vibe: { pedagogieDiscipline: 9, suiviAutonomie: 7, dataRessenti: 1 },
  },
];
